blog_edit_post:
    path:     /blog/edit/{id}
    defaults: { _controller: 'Blog::BlogAdminController::editPostAction' }

blog_add_post:
    path:     /blog/new
    defaults: { _controller: 'Blog::BlogAdminController::editPostAction' }

blog_delete_posts:
    path:     /blog/delete
    defaults: { _controller: 'Blog::BlogAdminController::deleteAction' }

blog_toggle_posts_published:
    path:     /blog/publish
    defaults: { _controller: 'Blog::BlogAdminController::togglePublishedAction' }

blog_admin_home:
  path: /blog
  defaults: { _controller: 'Blog::BlogAdminController::blogHomeAction' }

blog_finder:
  path: /blog/finder/{page}
  defaults: { page: 1, _controller: 'Blog::BlogAdminController::finderAction' }