blog_edit_post:
    path:     /blog/edit/{id}
    defaults: { _controller: 'Blog::BlogAdminController::editPostAction' }

blog_add_post:
    path:     /blog/new
    defaults: { _controller: 'Blog::BlogAdminController::editPostAction' }

blog_delete_posts:
    path:     /blog/delete
    defaults: { _controller: 'Blog::BlogAdminController::deleteAction' }

blog_toggle_posts_published:
    path:     /blog/publish
    defaults: { _controller: 'Blog::BlogAdminController::togglePublishedAction' }

blog_admin_home:
  path: /blog
  defaults: { _controller: 'Blog::BlogAdminController::blogHomeAction' }

blog_finder:
  path: /blog/finder/{page}
  defaults: { page: 1, _controller: 'Blog::BlogAdminController::finderAction' }

# Categories #
blog_manage_categories:
  path: /blog/categories
  defaults: { _controller: 'Blog::BlogAdminController::manageCategoriesAction', contentType: blog_post }

blog_save_categories_order:
  path: /blog/categories/save-order
  defaults: { _controller: Blog::BlogAdminController::saveOrderAction, contentType: blog_post }

blog_admin_add_category:
  path: /blog/categories/new
  defaults: { _controller: Blog::BlogAdminController::editCategoryAction, contentType: blog_post }

blog_admin_delete_category:
  path: /blog/categories/delete/{id}
  defaults: { _controller: Blog::BlogAdminController::deleteCategoryAction, contentType: blog_post }

blog_admin_edit_category:
  path: /blog/categories/edit/{id}
  defaults: { _controller: Blog::BlogAdminController::editCategoryAction, contentType: blog_post }
