name: Blog
namespace: AVCMS\Bundles\Blog

model:
  posts: Posts
  users: AVCMS\Bundles\Users\Model\Users

setup_class: BlogBundle

parent_bundle: Assets

template:
  blog_post: @AVBlog/blog_post.twig
  blog_home: @AVBlog/blog_home.twig