name: Blog
namespace: AVCMS\Bundles\Blog

require:
  - Admin
  - CmsFoundation
  - Users
  - Comments

services:
  - MarkdownServices

model:
  posts: Posts
  users: AVCMS\Bundles\Users\Model\Users

template:
  blog_post: @Blog/blog_post.twig
  blog_home: @Blog/blog_home.twig

user_settings:
  blog_posts_per_page:
      type: text
      label: Blog Posts Per Page
      help: The number of blog posts displayed on each page
      section: main
      validation:
        numeric:
          rule: Numeric

assets:
  bootstrap-markdown.js:
    env: admin
  markdown.js:
    env: admin
  to-markdown.js:
    env: admin

  bootstrap-markdown.min.css:
    env: admin

modules:
  blog_posts:
    name: Blog Posts
    description: A sortable list of blog posts
    controller: Blog::BlogModulesController::blogPostsModule
    cachable: true
    default_cache_time: 10
    accepted_template_types: [list_panel, none]
    user_settings:
      order:
        type: select
        label: Order
        choices:
          newest: Newest Posts
          popular: Popular Posts
        default: newest
      limit:
        type: text
        label: Number of posts to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: false

menu_items:
  admin:
    admin_blog_posts:
      target: blog_admin_home
      icon: glyphicon glyphicon-pencil
      type: route
      label: Blog

permissions:
  ADMIN_BLOG:
    default: deny
    name: Blog Administration
    description: Ability to manage blog posts

require:
  - CmsFoundation
  - Admin
  - Users