name: Blog
namespace: AVCMS\Bundles\Blog

required_bundles:
  - Admin

model:
  posts: Posts
  users: AVCMS\Bundles\Users\Model\Users

parent_bundle: Assets

template:
  blog_post: @Blog/blog_post.twig
  blog_home: @Blog/blog_home.twig