name: Blog
namespace: AVCMS\Bundles\Blog

require:
  - Framework
  - Admin
  - CmsFoundation
  - Users
  - Comments
  - Tags

model:
  posts: Posts
  users: AVCMS\Bundles\Users\Model\Users

comments:
  blog_post:
    name: Blog Post
    model: AVCMS\Bundles\Blog\Model\BlogPosts
    title_field: title
    frontend_route: blog_post
    frontend_route_params: [slug]

frontend_search:
  blog_posts:
    name: Blog Posts
    route: blog_archive

user_settings:
  blog_posts_per_page:
      type: text
      label: Blog Posts Per Page
      help: The number of blog posts displayed on each page
      section: main
      validation:
        numeric:
          rule: Numeric

modules:
  blog_posts:
    name: Blog Posts
    description: A sortable list of blog posts
    controller: Blog::BlogModulesController::blogPostsModule
    cachable: true
    default_cache_time: 10
    accepted_template_types: [list_panel, none]
    default_permissions: [ADMIN_BLOG]
    user_settings:
      order:
        type: select
        label: Order
        choices:
          newest: Newest Posts
          popular: Popular Posts
        default: newest
      limit:
        type: text
        label: Number of posts to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: false

menu_items:
  admin:
    admin_blog_posts:
      target: blog_admin_home
      icon: glyphicon glyphicon-pencil
      type: route
      label: Blog
      permission: ADMIN_BLOG

permissions:
  ADMIN_BLOG:
    name: Blog Administration
    description: Ability to manage blog posts

require:
  - CmsFoundation
  - Admin
  - Users