name: Blog
namespace: AVCMS\Bundles\Blog
toggle: true

require:
  - Framework
  - Admin
  - CmsFoundation
  - Users
  - Comments
  - Tags

services:
  - BlogServices

categories:
  blog_post:
    model: AVCMS\Bundles\Blog\Model\BlogCategories
    content_model: AVCMS\Bundles\Blog\Model\BlogPosts
    route_prefix: blog_

comments:
  blog_post:
    name: Blog Post
    model: AVCMS\Bundles\Blog\Model\BlogPosts
    title_field: title
    frontend_route: blog_post
    frontend_route_params: [slug]

frontend_search:
  blog_posts:
    name: Blog Posts
    route: blog_archive
    priority: 0

admin_settings_sections:
  blog: Blog

admin_settings:
  blog_posts_per_page:
      type: text
      label: Blog Posts Per Page
      help: The number of blog posts displayed on each page
      section: blog
      default: 10
      validation:
        numeric:
          rule: Numeric
  show_blog_hits:
    type: checkbox
    label: Show post hits
    help: Show the number of page hits each blog post has on the frontend
    section: blog
    default: true

modules:
  blog_posts:
    name: Blog Posts
    description: A sortable list of blog posts
    controller: Blog::BlogModulesController::blogPostsModule
    cachable: true
    cache_bust_model: BlogPosts
    default_cache_time: 3600
    accepted_template_types: [list_panel, none]
    admin_settings:
      order:
        type: select
        label: Order
        choices:
          newest: Newest Posts
          top_hits: Top Hits
        default: newest
      limit:
        type: text
        label: Number of posts to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: false
  blog_tags:
    name: Blog Tag Cloud
    description: A tag cloud for blog posts
    controller: Blog::BlogModulesController::tagsModule
    cachable: true
    default_cache_time: 43200
    accepted_template_types: [content, panel, none]
    admin_settings:
      limit:
        type: text
        label: Number of tags to display
        default: 40

menu_items:
  frontend:
    blog_home:
      label: Blog
      icon: glyphicon glyphicon-pencil
      type: route
      default_order: 10
      settings:
        route: blog_home
  admin:
    admin_blog_posts:
      icon: glyphicon glyphicon-pencil
      type: route
      label: Blog
      permission: ADMIN_BLOG
      default_order: 20
      settings:
        route: blog_admin_home
    admin_blog_categories:
      icon: glyphicon glyphicon-th-list
      type: route
      label: Categories
      permission: ADMIN_BLOG
      parent: admin_blog_posts
      settings:
        route: blog_manage_categories

permissions:
  ADMIN_BLOG:
    name: Blog Administration
    description: Ability to manage blog posts

require:
  - CmsFoundation
  - Admin
  - Users
