name: Blog
namespace: AVCMS\Bundles\Blog

model:
  posts: Posts
  users: AVCMS\Bundles\Users\Model\Users

template:
  blog_post: @Blog/blog_post.twig
  blog_home: @Blog/blog_home.twig

user_settings:
  blog_posts_per_page:
      type: text
      label: Blog Posts Per Page
      help: The number of blog posts displayed on each page
      section: main

assets:
  bootstrap-markdown.js:
    env: admin
  markdown.js:
    env: admin
  to-markdown.js:
    env: admin

  bootstrap-markdown.min.css:
    env: admin

require:
  - CmsFoundation
  - Admin
  - Users