name: Blog
namespace: AVCMS\Bundles\Blog

require:
  - Framework
  - Admin
  - CmsFoundation
  - Users
  - Comments
  - Tags

services:
  - BlogServices

model:
  posts: Posts
  users: AVCMS\Bundles\Users\Model\Users

comments:
  blog_post:
    name: Blog Post
    model: AVCMS\Bundles\Blog\Model\BlogPosts
    title_field: title
    frontend_route: blog_post
    frontend_route_params: [slug]

frontend_search:
  blog_posts:
    name: Blog Posts
    route: blog_archive

admin_settings_sections:
  blog: Blog

admin_settings:
  blog_posts_per_page:
      type: text
      label: Blog Posts Per Page
      help: The number of blog posts displayed on each page
      section: blog
      default: 10
      validation:
        numeric:
          rule: Numeric
  show_blog_hits:
    type: checkbox
    label: Show post hits
    help: Show the number of page hits each blog post has on the frontend
    section: blog
    default: true

modules:
  blog_posts:
    name: Blog Posts
    description: A sortable list of blog posts
    controller: Blog::BlogModulesController::blogPostsModule
    cachable: true
    cache_bust_model: BlogPosts
    default_cache_time: 3600
    accepted_template_types: [list_panel, none]
    admin_settings:
      order:
        type: select
        label: Order
        choices:
          newest: Newest Posts
          top_hits: Top Hits
        default: newest
      limit:
        type: text
        label: Number of posts to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: false

menu_items:
  admin:
    admin_blog_posts:
      icon: glyphicon glyphicon-pencil
      type: route
      label: Blog
      permission: ADMIN_BLOG
      default_order: 20
      settings:
        route: blog_admin_home

permissions:
  ADMIN_BLOG:
    name: Blog Administration
    description: Ability to manage blog posts

require:
  - CmsFoundation
  - Admin
  - Users
