name: Blog
namespace: AVCMS\Bundles\Blog

model:
  posts: Posts
  users: AVBlog\Bundles\Users\Model\Users

setup_class: BlogBundle

parent_bundle: Assets

route:
  blog_post: blog_post
  blog_edit_post: blog_edit_post

template:
  blog_post: @AVBlog/blog_post.twig
  blog_home: @AVBlog/blog_home.twig