blog_categories:
    bundle: Blog
    namespace: AVCMS\Bundles\Blog
    singular: blog_category
    plural: blog_categories
    uc_singular: 'Blog Category'
    uc_plural: 'Blog Categories'
    cc_singular: BlogCategory
    cc_plural: BlogCategories
    dash_singular: blog-category
    dash_plural: blog-categories
    admin_home_route: blog_categories_admin_home
    admin_finder_route: blog_categories_admin_finder
    admin_delete_route: blog_categories_admin_delete
    admin_edit_route: blog_categories_admin_edit
    admin_add_route: blog_categories_admin_add
    admin_controller: 'Blog::BlogCategoriesAdminController'
    finder_item_extra_buttons: ''
    database: blog_categories
    entity: AVCMS\Bundles\Blog\Model\BlogCategory
    admin_form: AVCMS\Bundles\Blog\Form\BlogCategoryAdminForm
    model_class: BlogCategories
    model_var_name: blogCategories
    title_field: name
