blog_home:
    path:     '/blog'
    defaults: { _controller: 'Blog::BlogController::blogArchiveAction', pageType: home }

blog_archive:
    path:     '/blog/archive/{page}'
    defaults: { _controller: 'Blog::BlogController::blogArchiveAction', page: 1 }

blog_post:
    path:     /blog/{slug}
    defaults: { _controller: 'Blog::BlogController::blogPostAction' }
