blog_home:
    path:     '/blog'
    defaults: { _controller: 'Blog::BlogController::blogArchiveAction' }

blog_archive:
    path:     '/blog/archive'
    defaults: { _controller: 'Blog::BlogController::blogArchiveAction' }

blog_post:
    path:     /blog/{slug}
    defaults: { _controller: 'Blog::BlogController::blogPostAction' }