referrals:
    bundle: Referrals
    namespace: AVCMS\Bundles\Referrals
    singular: referral
    plural: referrals
    uc_singular: Referral
    uc_plural: Referrals
    cc_singular: Referral
    cc_plural: Referrals
    dash_singular: referral
    dash_plural: referrals
    admin_home_route: referrals_admin_home
    admin_finder_route: referrals_admin_finder
    admin_delete_route: referrals_admin_delete
    admin_edit_route: referrals_admin_manage
    admin_add_route: referrals_admin_add
    admin_controller: 'Referrals::ReferralsAdminController'
    finder_item_extra_buttons: ''
    database: referrals
    entity: AVCMS\Bundles\Referrals\Model\Referral
    admin_form: AVCMS\Bundles\Referrals\Form\ReferralAdminForm
    model_class: Referrals
    model_var_name: referrals
    title_field: name
