directory_structure:
  - config
  - Controller
  - Model
  - Form
  - resources
  - resources/templates
  - Services

base_controller: AVCMS\Core\Controller\Controller
admin_controller: AVCMS\Bundles\Admin\Controller\AdminController

base_entity: AV\Model\Entity
base_model: AV\Model\Model

form_blueprint: AV\Form\FormBlueprint