directory_structure:
  - config
  - Controller
  - Model
  - templates
  - Form
  - resources
  - Services

base_controller: AVCMS\Core\Controller\Controller
admin_controller: AVCMS\Bundles\Admin\Controller\AdminController

base_entity: AVCMS\Core\Model\Entity
base_model: AVCMS\Core\Model\Model

form_blueprint: AVCMS\Core\Form\FormBlueprint