manage_reports:
  path: /reports
  defaults: { _controller: Reports::ReportsAdminController::manageReportsAction }

reports_finder:
  path: /reports/finder
  defaults: { _controller: Reports::ReportsAdminController::reportsFinderAction }

delete_reports:
  path: /reports/delete
  defaults: { _controller: Reports::ReportsAdminController::deleteReportsAction }
  methods: [POST]