name: Reports
namespace: AVCMS\Bundles\Reports

require:
  - Framework
  - CmsFoundation
  - Users

services:
  - ReportsServices

permissions:
  ADMIN_REPORTS:
      name: Manage Reports
      description: Ability to view & manage reports
  PERM_SEND_REPORTS:
      name: Send Reports
      description: Allows users to report site content like comments

assets:
  avcms_reports.js:
    env: frontend

modules:
  reports:
      name: Reports Info
      description: Info about current reports sent to the admin
      controller: Reports::ReportsModuleController::reportsAdminModule
      cachable: false
      accepted_template_types: [panel, none]
      type: admin

menu_items:
  admin:
    admin_reports:
      type: route
      target: manage_reports
      icon: glyphicon glyphicon-warning-sign
      label: Reports