name: Reports
namespace: AVCMS\Bundles\Reports

require:
  - Framework
  - CmsFoundation
  - Users

services:
  - ReportsServices

permissions:
  ADMIN_REPORTS:
    name: Manage Reports
    description: Ability to view & manage reports

assets:
  avcms_reports.js:
    env: frontend

menu_items:
  admin:
    admin_reports:
      type: route
      target: manage_reports
      icon: glyphicon glyphicon-warning-sign
      label: Reports