reports:
    bundle: Reports
    namespace: AVCMS\Bundles\Reports
    singular: report
    plural: reports
    uc_singular: Report
    uc_plural: Reports
    cc_singular: Report
    cc_plural: Reports
    dash_singular: report
    dash_plural: reports
    admin_home_route: reports_admin_home
    admin_finder_route: reports_admin_finder
    admin_delete_route: reports_admin_delete
    admin_edit_route: reports_admin_edit
    admin_add_route: reports_admin_add
    admin_controller: 'Reports::ReportsAdminController'
    finder_item_extra_buttons: ''
    database: reports
    entity: AVCMS\Bundles\Reports\Model\Report
    admin_form: AVCMS\Bundles\Reports\Form\ReportAdminForm
    model_class: Reports
    model_var_name: reports
    title_field: id
