

groups_admin_edit:
    path:     /groups/edit/{id}
    defaults: { _controller: 'TestBundle::GroupsAdminController::editAction' }

groups_admin_add:
    path:     /groups/new
    defaults: { _controller: 'TestBundle::GroupsAdminController::editAction' }

groups_admin_delete:
    path:     /groups/delete
    defaults: { _controller: 'TestBundle::GroupsAdminController::deleteAction' }

groups_admin_home:
  path: /groups
  defaults: { _controller: 'TestBundle::GroupsAdminController::homeAction' }

groups_admin_finder:
  path: /groups/finder/{page}
  defaults: { page: 1, _controller: 'TestBundle::GroupsAdminController::finderAction' }