Mexico:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: Mex
    plural: Mexico
    uc_singular: Mex
    uc_plural: Mexico
    cc_singular: Mex
    cc_plural: Mexico
    admin_home_route: Mexico_admin_home
    admin_finder_route: Mexico_admin_finder
    admin_delete_route: Mexico_admin_delete
    admin_edit_route: Mexico_admin_edit
    admin_add_route: Mexico_admin_add
    admin_controller: 'TestBundle::MexicoAdminController'
    finder_item_extra_buttons: ''
    database: fog
    entity: AVCMS\Bundles\TestBundle\Model\Mex
    admin_form: AVCMS\Bundles\TestBundle\Form\MexAdminForm
    model_class: Mexico
    model_var_name: mexico
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, fog_id: { entity: '1', form_field: none, form_label: 'Fog Id' }, name: { entity: '1', form_field: text, form_label: Name }, description: { entity: '1', form_field: none, form_label: Description }, thumb_url: { entity: '1', form_field: none, form_label: 'Thumb Url' }, file_url: { entity: '1', form_field: none, form_label: 'File Url' }, width: { entity: '1', form_field: none, form_label: Width }, height: { entity: '1', form_field: none, form_label: Height }, author: { entity: '1', form_field: none, form_label: Author }, author_link: { entity: '1', form_field: none, form_label: 'Author Link' }, category: { entity: '1', form_field: none, form_label: Category }, visible: { entity: '1', form_field: none, form_label: Visible }, instructions: { entity: '1', form_field: none, form_label: Instructions }, featured: { entity: '1', form_field: none, form_label: Featured }, tags: { entity: '1', form_field: none, form_label: Tags }, highscores: { entity: '1', form_field: none, form_label: Highscores } }
Mexi:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: Mex
    plural: Mexi
    uc_singular: Mex
    uc_plural: Mexi
    cc_singular: Mex
    cc_plural: Mexi
    admin_home_route: Mexi_admin_home
    admin_finder_route: Mexi_admin_finder
    admin_delete_route: Mexi_admin_delete
    admin_edit_route: Mexi_admin_edit
    admin_add_route: Mexi_admin_add
    admin_controller: 'TestBundle::MexiAdminController'
    finder_item_extra_buttons: ''
    database: fog
    entity: AVCMS\Bundles\TestBundle\Model\Mex
    admin_form: AVCMS\Bundles\TestBundle\Form\MexAdminForm
    model_class: Mexi
    model_var_name: mexi
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, fog_id: { entity: '1', form_field: none, form_label: 'Fog Id' }, name: { entity: '1', form_field: none, form_label: Name }, description: { entity: '1', form_field: none, form_label: Description }, thumb_url: { entity: '1', form_field: none, form_label: 'Thumb Url' }, file_url: { entity: '1', form_field: none, form_label: 'File Url' }, width: { entity: '1', form_field: none, form_label: Width }, height: { entity: '1', form_field: none, form_label: Height }, author: { entity: '1', form_field: none, form_label: Author }, author_link: { entity: '1', form_field: none, form_label: 'Author Link' }, category: { entity: '1', form_field: none, form_label: Category }, visible: { entity: '1', form_field: none, form_label: Visible }, instructions: { entity: '1', form_field: none, form_label: Instructions }, featured: { entity: '1', form_field: none, form_label: Featured }, tags: { entity: '1', form_field: none, form_label: Tags }, highscores: { entity: '1', form_field: none, form_label: Highscores } }
Zeds:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: Zed
    plural: Zeds
    uc_singular: Zed
    uc_plural: Zeds
    cc_singular: Zed
    cc_plural: Zeds
    admin_home_route: Zeds_admin_home
    admin_finder_route: Zeds_admin_finder
    admin_delete_route: Zeds_admin_delete
    admin_edit_route: Zeds_admin_edit
    admin_add_route: Zeds_admin_add
    admin_controller: 'TestBundle::ZedsAdminController'
    finder_item_extra_buttons: ''
    database: fog
    entity: AVCMS\Bundles\TestBundle\Model\Zed
    admin_form: AVCMS\Bundles\TestBundle\Form\ZedAdminForm
    model_class: Zeds
    model_var_name: zeds
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, fog_id: { entity: '1', form_field: none, form_label: 'Fog Id' }, name: { entity: '1', form_field: text, form_label: Name }, description: { entity: '1', form_field: none, form_label: Description }, thumb_url: { entity: '1', form_field: none, form_label: 'Thumb Url' }, file_url: { entity: '1', form_field: none, form_label: 'File Url' }, width: { entity: '1', form_field: none, form_label: Width }, height: { entity: '1', form_field: none, form_label: Height }, author: { entity: '1', form_field: none, form_label: Author }, author_link: { entity: '1', form_field: none, form_label: 'Author Link' }, category: { entity: '1', form_field: none, form_label: Category }, visible: { entity: '1', form_field: none, form_label: Visible }, instructions: { entity: '1', form_field: none, form_label: Instructions }, featured: { entity: '1', form_field: none, form_label: Featured }, tags: { entity: '1', form_field: none, form_label: Tags }, highscores: { entity: '1', form_field: none, form_label: Highscores } }
Lols:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: Lol
    plural: Lols
    uc_singular: Lol
    uc_plural: Lols
    cc_singular: Lol
    cc_plural: Lols
    admin_home_route: Lols_admin_home
    admin_finder_route: Lols_admin_finder
    admin_delete_route: Lols_admin_delete
    admin_edit_route: Lols_admin_edit
    admin_add_route: Lols_admin_add
    admin_controller: 'TestBundle::LolsAdminController'
    finder_item_extra_buttons: ''
    database: fog
    entity: AVCMS\Bundles\TestBundle\Model\Lol
    admin_form: AVCMS\Bundles\TestBundle\Form\LolAdminForm
    model_class: Lols
    model_var_name: lols
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, fog_id: { entity: '1', form_field: none, form_label: 'Fog Id' }, name: { entity: '1', form_field: text, form_label: Name }, description: { entity: '1', form_field: none, form_label: Description }, thumb_url: { entity: '1', form_field: none, form_label: 'Thumb Url' }, file_url: { entity: '1', form_field: none, form_label: 'File Url' }, width: { entity: '1', form_field: none, form_label: Width }, height: { entity: '1', form_field: none, form_label: Height }, author: { entity: '1', form_field: none, form_label: Author }, author_link: { entity: '1', form_field: none, form_label: 'Author Link' }, category: { entity: '1', form_field: none, form_label: Category }, visible: { entity: '1', form_field: none, form_label: Visible }, instructions: { entity: '1', form_field: none, form_label: Instructions }, featured: { entity: '1', form_field: none, form_label: Featured }, tags: { entity: '1', form_field: none, form_label: Tags }, highscores: { entity: '1', form_field: none, form_label: Highscores } }
tokens:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: token
    plural: tokens
    uc_singular: Token
    uc_plural: Tokens
    cc_singular: Token
    cc_plural: Tokens
    dash_singular: token
    dash_plural: tokens
    admin_home_route: tokens_admin_home
    admin_finder_route: tokens_admin_finder
    admin_delete_route: tokens_admin_delete
    admin_edit_route: tokens_admin_edit
    admin_add_route: tokens_admin_add
    admin_controller: 'TestBundle::TokensAdminController'
    finder_item_extra_buttons: ''
    database: sessions
    entity: AVCMS\Bundles\TestBundle\Model\Token
    admin_form: AVCMS\Bundles\TestBundle\Form\TokenAdminForm
    model_class: Tokens
    model_var_name: tokens
    title_field: id
    columns: { class: { entity: '1', form_field: none, form_label: Class }, username: { entity: '1', form_field: none, form_label: Username }, series: { entity: '1', form_field: none, form_label: Series }, token_value: { entity: '1', form_field: none, form_label: 'Token Value' }, last_used: { entity: '1', form_field: none, form_label: 'Last Used' } }
Users:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: User
    plural: Users
    uc_singular: User
    uc_plural: Users
    cc_singular: User
    cc_plural: Users
    dash_singular: User
    dash_plural: Users
    admin_home_route: Users_admin_home
    admin_finder_route: Users_admin_finder
    admin_delete_route: Users_admin_delete
    admin_edit_route: Users_admin_edit
    admin_add_route: Users_admin_add
    admin_controller: 'TestBundle::UsersAdminController'
    finder_item_extra_buttons: ''
    database: users
    entity: AVCMS\Bundles\TestBundle\Model\User
    admin_form: AVCMS\Bundles\TestBundle\Form\UserAdminForm
    model_class: Users
    model_var_name: users
    title_field: username
    columns: { id: { entity: '1', form_field: none, form_label: Id }, username: { entity: '1', form_field: text, form_label: Username }, password: { entity: '1', form_field: none, form_label: Password }, email: { entity: '1', form_field: text, form_label: Email }, email_validated: { entity: '1', form_field: none, form_label: 'Email Validated' }, about: { entity: '1', form_field: textarea, form_label: About }, role_list: { entity: '1', form_field: select, form_label: Groups }, location: { entity: '1', form_field: text, form_label: Location }, interests: { entity: '1', form_field: textarea, form_label: Interests }, website: { entity: '1', form_field: text, form_label: Website }, joined: { entity: '1', form_field: text, form_label: Joined }, avatar: { entity: '1', form_field: text, form_label: Avatar }, facebook: { entity: '1', form_field: none, form_label: Facebook }, facebook_id: { entity: '1', form_field: none, form_label: 'Facebook Id' }, lastip: { entity: '1', form_field: none, form_label: Lastip }, slug: { entity: '1', form_field: text, form_label: Slug }, last_activity: { entity: '1', form_field: text, form_label: 'Last Activity' }, timezone: { entity: '1', form_field: none, form_label: Timezone }, cover_image: { entity: '1', form_field: text, form_label: 'Cover Image' } }
users:
    bundle: TestBundle
    namespace: AVCMS\Bundles\TestBundle
    singular: user
    plural: users
    uc_singular: User
    uc_plural: Users
    cc_singular: User
    cc_plural: Users
    dash_singular: user
    dash_plural: users
    admin_home_route: users_admin_home
    admin_finder_route: users_admin_finder
    admin_delete_route: users_admin_delete
    admin_edit_route: users_admin_edit
    admin_add_route: users_admin_add
    admin_controller: 'TestBundle::UsersAdminController'
    finder_item_extra_buttons: ''
    database: users
    entity: AVCMS\Bundles\TestBundle\Model\User
    admin_form: AVCMS\Bundles\TestBundle\Form\UserAdminForm
    model_class: Users
    model_var_name: users
    title_field: username
    columns: { id: { entity: '1', form_field: none, form_label: Id }, username: { entity: '1', form_field: text, form_label: Username }, password: { entity: '1', form_field: text, form_label: Password }, email: { entity: '1', form_field: text, form_label: Email }, email_validated: { entity: '1', form_field: checkbox, form_label: 'Email Validated' }, about: { entity: '1', form_field: textarea, form_label: About }, role_list: { entity: '1', form_field: text, form_label: Groups }, location: { entity: '1', form_field: text, form_label: Location }, interests: { entity: '1', form_field: textarea, form_label: Interests }, website: { entity: '1', form_field: text, form_label: Website }, joined: { entity: '1', form_field: text, form_label: Joined }, avatar: { entity: '1', form_field: text, form_label: Avatar }, facebook: { entity: '1', form_field: none, form_label: Facebook }, facebook_id: { entity: '1', form_field: none, form_label: 'Facebook Id' }, lastip: { entity: '1', form_field: none, form_label: Lastip }, slug: { entity: '1', form_field: text, form_label: Slug }, last_activity: { entity: '1', form_field: none, form_label: 'Last Activity' }, timezone: { entity: '1', form_field: none, form_label: Timezone }, cover_image: { entity: '1', form_field: text, form_label: 'Cover Image' } }
