name: LikeDislike
namespace: AVCMS\Bundles\LikeDislike
require:
    - Framework

services:
    - RatingsServices

assets:
    avcms_like_dislike.js:
        env: frontend

admin_settings:
  enable_ratings:
    type: checkbox
    default: 1
    label: Enable Like/Dislike ratings
    help: Enable Like/Dislike ratings for all content
    section: main
  enable_unregistered_ratings:
    type: checkbox
    default: 0
    label: Allow unregistered users to vote
    help: Users won't need to be logged in to Like/Dislike content. It will be done by IP.
    section: main
