name: LikeDislike
namespace: AVCMS\Bundles\LikeDislike
require:
    - Framework

services:
    - RatingsServices

assets:
    avcms_like_dislike.js:
        env: frontend

admin_settings:
  enable_ratings:
    type: checkbox
    default: 1
    label: Enable Like/Dislike ratings
    help: Enable Like/Dislike ratings for all content
    section: main
