Ratings:
    bundle: LikeDislike
    namespace: AVCMS\Bundles\LikeDislike
    singular: Rating
    plural: Ratings
    uc_singular: Rating
    uc_plural: Ratings
    cc_singular: Rating
    cc_plural: Ratings
    dash_singular: Rating
    dash_plural: Ratings
    admin_home_route: Ratings_admin_home
    admin_finder_route: Ratings_admin_finder
    admin_delete_route: Ratings_admin_delete
    admin_edit_route: Ratings_admin_edit
    admin_add_route: Ratings_admin_add
    admin_controller: 'LikeDislike::RatingsAdminController'
    finder_item_extra_buttons: ''
    database: ratings
    entity: AVCMS\Bundles\LikeDislike\Model\Rating
    admin_form: AVCMS\Bundles\LikeDislike\Form\RatingAdminForm
    model_class: Ratings
    model_var_name: ratings
    title_field: id
