wss_importer_home:
  path: /import
  defaults: { _controller: WssImporter::WssImporterController::importerHomeAction }

wss_importer_run:
  path: /import/run/{stage}/{run}
  defaults: { _controller: WssImporter::WssImporterController::doImportAction, stage: wallpapers, run: 1 }
