name: CkEditor
namespace: AVCMS\Bundles\CkEditor

require:
  - Framework
  - CmsFoundation
  - Admin

assets:
  ckeditor/ckeditor.js:
    env: admin
    compile: false
  ckeditor/adapters/jquery.js:
    env: admin
    compile: false
  avcms_ckeditor_admin.js:
    env: admin
    priority: 88