translation_helper:
  path: /my-translations
  defaults: { _controller: TranslationHelper::TranslationHelperController::myTranslationsHomeAction }

translate:
  path: /translations/{id}
  defaults: { _controller: TranslationHelper::TranslationHelperController::translationAction }

translate_bundle:
  path: /translations/{id}/edit/{bundle}
  defaults: { _controller: TranslationHelper::TranslationHelperController::bundleTranslateAction }

clone_translation:
  path: /translations/clone/{id}
  defaults: { _controller: TranslationHelper::TranslationHelperController::cloneAction }

download_translation:
  path: /translations/download/{id}
  defaults: { _controller: TranslationHelper::TranslationHelperController::downloadTranslationAction }

add_translation:
  path: /my-translations/add
  defaults: { _controller: TranslationHelper::TranslationHelperController::addEditTranslationAction }

edit_translation:
  path: /my-translations/edit/{id}
  defaults: { _controller: TranslationHelper::TranslationHelperController::addEditTranslationAction }

browse_translations:
  path: /translations
  defaults: { _controller: TranslationHelper::TranslationHelperController::browseTranslationsAction }
