name: Points
namespace: AVCMS\Bundles\Points
toggle: true
require:
    - Framework

services:
  - PointsServices

assets:
  avcms_points.js:
    env: frontend

admin_settings_sections:
  points: Points

admin_settings:
  points_name:
    type: text
    label: Points Name
    help: Rename "points" to something else
    section: points
    default: Points
  game_points:
    type: text
    label: Game Points
    help: The number of points a user gets when playing a game for 2 minutes
    section: points
    default: 10
    validation:
      numeric:
        rule: Numeric
  rating_points:
    type: text
    label: Rating Points
    help: The number of points a user gets when rating content (like or dislike)
    section: points
    default: 10
    validation:
      numeric:
        rule: Numeric
  comment_points:
    type: text
    label: Comment Points
    help: The number of points a user gets when making a comment
    section: points
    default: 10
    validation:
      numeric:
        rule: Numeric
  report_points:
    type: text
    label: Report Points
    help: The number of points a user gets when making sending a report
    section: points
    default: 15
    validation:
      numeric:
        rule: Numeric

modules:
  top_points:
    name: Top Points
    description: Shows the users with the most points
    controller: Points::PointsModulesController::topPointsModule
    cachable: true
    default_cache_time: 0
    accepted_template_types: [list_panel, none]
    admin_settings:
      limit:
        type: text
        label: Number of users to display
        default: 10
        validation:
          numeric:
            rule: Numeric
