bundle_asset:
  path: /bundle_asset
  defaults: { _controller: Assets::AssetsController::getAssetAction }

template_asset:
  path: /template_asset/{template}/{type}/{asset_file}
  defaults: { _controller: Assets::AssetsController::getAssetAction }

generate_assets:
  path: /generate_assets
  defaults: { _controller: Assets::AssetsController::generateAssetsAction }