info:
  name: Wallpaper Site Script
  version: '2.0.8'
  id: wallpapersitescript
  url: http://www.avscripts.net/wallpaperscript

bundle_dirs:
  AV\Bundles: src/AV/Bundles
  AVCMS\Bundles: src/AVCMS/Bundles
  AVCMS\BundlesDev: src/AVCMS/BundlesDev

license:
  length: 15
  prefix: wss

default_content_installer: WallpaperDefaultContentInstaller
