info:
  name: Wallpaper Site Script
  version: '2.0'
  id: wallpapersitescript
  url: http://www.avscripts.net/wallpaperscript

bundle_dirs:
  - src/AV/Bundles
  - src/AVCMS/Bundles
  - src/AVCMS/BundlesDev

license:
  length: 15
  prefix: wss

default_content_installer: WallpaperDefaultContentInstaller
