Framework:
    enabled: true
Twig:
    enabled: true
Form:
    enabled: true
Model:
    enabled: true
CmsFoundation:
    enabled: true
Users:
    enabled: true
Admin:
    enabled: true
Blog:
    enabled: true
Tags:
    enabled: true
Assets:
    enabled: true
Translation:
    enabled: true
Comments:
    enabled: true
CkEditor:
    enabled: true
Reports:
    enabled: true
CmsErrorHandler:
    enabled: true
Wallpapers:
    enabled: true
FileUpload:
    enabled: true
