Framework:
    enabled: true
CmsFoundation:
    enabled: true
Users:
    enabled: true
Admin:
    enabled: true
Blog:
    enabled: true
Tags:
    enabled: true
Assets:
    enabled: true
Twig:
    enabled: true
