redirect_game_category:
  path: /{category}/{page}
  defaults: { _controller: CmsFoundation::RedirectController::redirectAction, page: 1, route: game_category }
  requirements:
    page:  \d+

redirect_game_category_with_sort:
  path: /{category}/{order}/{page}
  defaults: { _controller: CmsFoundation::RedirectController::redirectAction, page: 1, route: game_category }
  requirements:
    page:  \d+

redirect_play_game:
  path: /{category_name}/{slug}
  defaults: { _controller: CmsFoundation::RedirectController::redirectAction, route: play_game, ignoreAttributes: [category_name] }
