name: ErrorHandler
namespace: AVCMS\Bundles\CmsErrorHandler

require:
  - Framework
  - CmsFoundation

services:
  - ErrorHandlerServices

container_params:
  error_controller: AVCMS\Bundles\CmsErrorHandler\Controller\ErrorController::exceptionAction