review_bundle_translations:
  path: /dev/translations/{bundle}
  defaults: { _controller: DevTools::TranslationExtractionController::reviewBundleTranslations }

save_strings:
  path: /dev/save-translations
  defaults: { _controller: DevTools::TranslationExtractionController::saveStringsAction }

twig_namespaces:
  path: /dev/twig-namespaces
  defaults: { _controller: DevTools::MiscToolsController::twigNamespacesForPhpStormAction }

split_translations:
  path: /dev/split-translations
  defaults: { _controller: DevTools::TranslationExtractionController::splitterAction }
