review_bundle_translations:
  path: /dev/translations/{bundle}
  defaults: { _controller: DevTools::TranslationExtractionController::reviewBundleTranslations }

save_strings:
  path: /dev/save-translations
  defaults: { _controller: DevTools::TranslationExtractionController::saveStringsAction }