wallpapers_admin_edit:
    path:     /wallpapers/edit/{id}
    defaults: { _controller: 'Wallpapers::WallpapersAdminController::editAction' }

wallpapers_admin_add:
    path:     /wallpapers/new
    defaults: { _controller: 'Wallpapers::WallpapersAdminController::editAction' }

wallpapers_admin_delete:
    path:     /wallpapers/delete
    defaults: { _controller: 'Wallpapers::WallpapersAdminController::deleteAction' }

wallpapers_admin_home:
  path: /wallpapers
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::homeAction' }

wallpapers_admin_finder:
  path: /wallpapers/finder/{page}
  defaults: { page: 1, _controller: 'Wallpapers::WallpapersAdminController::finderAction' }

wallpapers_admin_find_files:
  path: /wallpapers/find-files
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::findFilesAction' }

wallpapers_admin_upload:
  path: /wallpapers/upload
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::uploadFilesAction' }

wallpapers_manage_categories:
  path: /wallpapers/categories
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::manageCategoriesAction', contentType: wallpaper }

wallpapers_save_categories_order:
  path: /wallpapers/categories/save-order
  defaults: { _controller: Wallpapers::WallpapersAdminController::saveOrderAction, contentType: wallpaper }
