wallpapers_admin_edit:
    path:     /wallpapers/edit/{id}
    defaults: { _controller: 'Wallpapers::WallpapersAdminController::editAction' }

wallpapers_admin_add:
    path:     /wallpapers/new
    defaults: { _controller: 'Wallpapers::WallpapersAdminController::editAction' }

wallpapers_admin_delete:
    path:     /wallpapers/delete
    defaults: { _controller: 'Wallpapers::WallpapersAdminController::deleteAction' }

wallpapers_admin_home:
  path: /wallpapers
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::homeAction' }

wallpapers_admin_finder:
  path: /wallpapers/finder/{page}
  defaults: { page: 1, _controller: 'Wallpapers::WallpapersAdminController::finderAction' }

wallpapers_admin_find_files:
  path: /wallpapers/find-files
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::findFilesAction' }

wallpapers_admin_upload:
  path: /wallpapers/upload
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::uploadFilesAction' }

wallpapers_manage_categories:
  path: /wallpapers/categories
  defaults: { _controller: 'Wallpapers::WallpapersAdminController::manageCategoriesAction', contentType: wallpaper }

wallpapers_save_categories_order:
  path: /wallpapers/categories/save-order
  defaults: { _controller: Wallpapers::WallpapersAdminController::saveOrderAction, contentType: wallpaper }

wallpapers_admin_add_category:
  path: /wallpapers/categories/new
  defaults: { _controller: Wallpapers::WallpapersAdminController::editCategoryAction, contentType: wallpaper }

wallpapers_admin_delete_category:
  path: /wallpapers/categories/delete/{id}
  defaults: { _controller: Wallpapers::WallpapersAdminController::deleteCategoryAction, contentType: wallpaper }

wallpapers_admin_edit_category:
  path: /wallpapers/categories/edit/{id}
  defaults: { _controller: Wallpapers::WallpapersAdminController::editCategoryAction, contentType: wallpaper }

wallpapers_grab_file:
  path: /wallpapers/grab-file
  defaults: { _controller: Wallpapers::WallpapersAdminController::grabFileAction }

wallpapers_manage_resolutions:
  path: /wallpapers/manage-resolutions
  defaults: { _controller: Wallpapers::WallpapersAdminController::editResolutionsAction }

wallpapers_admin_toggle_published:
  path: /wallpapers/publish
  defaults: { _controller: Wallpapers::WallpapersAdminController::togglePublishedAction }


wallpaper_bulk_import:
    path:     /wallpapers-bulk-import/import/{folder}
    defaults: { _controller: 'Wallpapers::WallpapersBulkImportAdminController::importAction' }

wallpaper_bulk_import_admin_delete:
    path:     /wallpapers-bulk-import/delete
    defaults: { _controller: 'Wallpapers::WallpapersBulkImportAdminController::deleteAction' }

wallpaper_bulk_import_admin_home:
  path: /wallpapers-bulk-import
  defaults: { _controller: 'Wallpapers::WallpapersBulkImportAdminController::homeAction' }

wallpaper_bulk_import_admin_finder:
  path: /wallpapers-bulk-import/finder/{page}
  defaults: { page: 1, _controller: 'Wallpapers::WallpapersBulkImportAdminController::finderAction' }

wallpapers_bulk_upload:
  path: /wallpapers-bulk-import/upload
  defaults: { _controller: 'Wallpapers::WallpapersBulkImportAdminController::bulkUploadAction' }

wallpapers_bulk_import_new_folder:
  path: /wallpapers-bulk-import/add-folder
  defaults: { _controller: 'Wallpapers::WallpapersBulkImportAdminController::addFolderAction' }
