name: Wallpapers
namespace: AVCMS\Bundles\Wallpapers
require:
    - Framework

services:
    - WallpaperServices

assets:
  avcms_wallpapers.js:
    env: admin
    priority: 50

menu_items:
    admin:
        wallpapers_admin:
            label: Wallpapers
            icon: glyphicon glyphicon-picture
            type: route
            target: wallpapers_admin_home
            default_order: 80
        wallpapers_bulk_admin:
          label: Bulk Import
          icon: glyphicon glyphicon-import
          type: route
          target: wallpaper_bulk_import_admin_home
          parent: wallpapers_admin

categories:
    wallpaper:
        model: AVCMS\Bundles\Wallpapers\Model\WallpaperCategories
        content_model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
        browser_template: @Wallpapers/wallpapers_browser.twig
        route_prefix: wallpapers_

frontend_search:
  wallpapers:
    name: Wallpapers
    route: browse_wallpapers

comments:
  wallpaper:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
    title_field: name
    frontend_route: wallpaper_details
    frontend_route_params: [slug]

modules:
  wallpapers:
    name: Wallpapers
    description: A sortable list of wallpapers
    controller: Wallpapers::WallpaperModulesController::wallpapersListModule
    cachable: true
    cache_bust_model: Wallpapers
    default_cache_time: 10000
    accepted_template_types: [list_panel, none]
    user_settings:
      order:
        type: select
        label: Order
        choices:
          newest: Newest
          top_hits: Top Hits
        default: newest
      limit:
        type: text
        label: Number of wallpapers to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: 0
      show_hits:
        type: checkbox
        label: Show Hits
        default: 1
      show_downloads:
        type: checkbox
        label: Show Downloads
        default: 1
      show_category:
        type: checkbox
        label: Show Category
        default: 1

config:
    wallpapers_dir: webmaster/wallpapers
    web_dir: wallpapers
