name: Wallpapers
namespace: AVCMS\Bundles\Wallpapers
require:
    - Framework

services:
    - WallpaperServices

menu_items:
    admin:
        wallpapers_admin:
            label: Wallpapers
            icon: glyphicon glyphicon-picture
            type: route
            target: wallpapers_admin_home
            default_order: 80

categories:
    wallpaper:
        model: AVCMS\Bundles\Wallpapers\Model\WallpaperCategories
        content_model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
        browser_template: @Wallpapers/wallpapers_browser.twig
        route_prefix: wallpapers_

config:
    wallpapers_dir: webmaster/wallpapers
