name: Wallpapers
namespace: AVCMS\Bundles\Wallpapers
toggle: true
require:
    - Framework

services:
    - WallpaperServices

assets:
  avcms_wallpapers_admin.js:
    env: admin
    priority: 50
  avcms_wallpapers_frontend.js:
    env: frontend

admin_settings_sections:
  wallpapers: Wallpapers
  browse_wallpapers: Browse Wallpapers

admin_settings:
  show_higher_resolutions:
    type: checkbox
    label: Show resolutions higher than the source image
    help: If turned on, all resolutions will be displayed for all wallpapers
    section: wallpapers
    default: false
  browse_wallpaper_columns:
    type: select
    label: Browse Wallpaper Columns
    help: How many columns of wallpapers to show when in the main browse wallpapers pages
    section: browse_wallpapers
    choices:
      1: 1
      2: 2
      3: 3
      4: 4
    choices_translate: false
    default: 2
  browse_wallpapers_per_page:
    type: text
    label: Wallpapers Per Page
    help: How many wallpapers to show when in the main browse wallpapers pages
    section: wallpapers
    default: 12
    validation:
      numeric:
        rule: Numeric
  wallpaper_image_manipulation_library:
    type: select
    label: Image Library
    help: The underlying image manipulation library that should be used
    section: wallpapers
    default: Gd
    choices:
      Gd: Gd
      Imagick: Imagick
  wallpaper_image_cache_limit:
    type: select
    label: Image cache limit
    help: Limit the number of wallpaper resolutions that are cached before they are cleared. Only enable if you are running out of disk space.
    section: wallpapers
    default: 0
    choices_translate: false
    choices:
      0: No limit
      1: 1
      2: 2
      3: 3
      4: 4
      5: 5
      8: 8
      10: 10
  wallpaper_thumbnail_quality:
    type: text
    label: Thumbnail image quality
    help: Between 50 & 100, 100 being better quality
    section: wallpapers
    default: 80
    validation:
      numeric:
        rule: Numeric
  wallpaper_default_thumbnail_resolution:
    type: radio
    label: Default thumbnail resolution
    help: Set the default resolution for thumbnail images
    section: wallpapers
    default: md
    choices:
      sm: Small
      md: Medium
  wallpapers_allow_uploads:
    type: checkbox
    label: Allow Wallpaper Submissions
    help: Allow users to submit wallpapers to your site for admins to review
    section: wallpapers
    default: 1
  wallpapers_max_submissions:
    type: text
    label: Maximum User Submissions
    help: The maximum amount of wallpapers a user can submit for review. They can submit more after an admin has accepted their existing submissions.
    section: wallpapers
    default: 10
    validation:
      numeric:
        rule: Numeric

  show_wallpaper_name:
    type: checkbox
    label: Show Wallpaper Name
    default: 1
    section: browse_wallpapers
  show_wallpaper_ratings:
    type: checkbox
    label: Show Wallpaper Ratings
    default: 1
    section: browse_wallpapers
  show_wallpaper_hits:
    type: checkbox
    label: Show Wallpaper Hits
    default: 1
    section: browse_wallpapers
  show_wallpaper_date:
    type: checkbox
    label: Show Publish Date
    default: 0
    section: browse_wallpapers
  show_wallpaper_category:
    type: checkbox
    label: Show Category
    default: 0
    section: browse_wallpapers
  show_wallpaper_comments:
    type: checkbox
    label: Show Comments
    default: 1
    section: browse_wallpapers
  wallpapers_home_meta_description:
      type: textarea
      label: Wallpapers homepage meta description
      section: wallpapers

menu_items:
  frontend:
    wallpaper_categories:
        label: Wallpapers
        icon: glyphicon glyphicon-picture
        type: wallpaper_categories
        default_order: 2
        settings:
          display: child
    wallpaper_submissions:
      label: Submit Wallpaper
      icon: glyphicon glyphicon-upload
      type: route
      admin_setting: wallpapers_allow_uploads
      settings:
        route: wallpaper_submit
  admin:
      wallpapers_admin:
          label: Wallpapers
          icon: glyphicon glyphicon-picture
          type: route
          default_order: 2
          settings:
            route: wallpapers_admin_home
      wallpapers_bulk_admin:
        label: Bulk Import
        icon: glyphicon glyphicon-import
        type: route
        parent: wallpapers_admin
        settings:
          route: wallpaper_bulk_import_admin_home
      wallpapers_categories_admin:
        label: Categories
        icon: glyphicon glyphicon-th-list
        type: route
        parent: wallpapers_admin
        settings:
          route: wallpapers_manage_categories
      wallpapers_resolutions_admin:
        label: Resolutions
        icon: glyphicon glyphicon-fullscreen
        type: route
        parent: wallpapers_admin
        settings:
          route: wallpapers_manage_resolutions
      wallpaper_submissions_admin:
        label: Submissions
        icon: glyphicon glyphicon-inbox
        type: route
        parent: wallpapers_admin
        settings:
          route: wallpaper_submissions_admin_home

categories:
    wallpaper:
        model: AVCMS\Bundles\Wallpapers\Model\WallpaperCategories
        content_model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
        route_prefix: wallpapers_

frontend_search:
  wallpapers:
    name: Wallpapers
    route: browse_wallpapers
    priority: 10

comments:
  wallpaper:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
    title_field: name
    frontend_route: wallpaper_details
    frontend_route_params: [slug]

reports:
  wallpapers:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
    route: wallpapers_admin_edit
    title_field: name
    route_params: [id]

ratings:
  wallpaper:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers

permissions:
  ADMIN_WALLPAPERS:
    name: Wallpapers Administration
    description: Manage wallpapers in the admin panel
  PERM_SUBMIT_WALLPAPERS:
    name: Submit Wallpapers
    description: Ability for users to submit wallpapers for review by an admin

module_positions:
  wallpapers_home:
    name: Wallpapers Homepage
    description: The wallpapers homepage
    environment: frontend
    global_modules: 1
    type: content
  wallpaper_details:
    name: Wallpaper Details Lower
    description: The wallpaper details page, underneath the resolutions
    environment: frontend

modules:
  wallpapers:
    name: Wallpapers
    description: A sortable list of wallpapers
    controller: Wallpapers::WallpaperModulesController::wallpapersModule
    cachable: true
    cache_bust_model: Wallpapers
    default_cache_time: 3600
    accepted_template_types: [content, panel, list_panel, none]
    admin_settings:
      filter:
        type: select
        label: Filter
        help: If "User's Likes" is selected, the module will show the likes of a user if one is passed to the module position (like on a users profile). Otherwise it will show the active user's likes.
        default: none
        choices:
          none: None
          featured: Featured
          likes: User's Likes
      order:
        type: select
        label: Order
        choices:
          publish-date-newest: Newest
          top-hits: Top Hits
          top-downloads: Top Downloads
          liked: Most Liked
          random: Random
        default: newest
      layout:
        type: select
        label: Layout
        choices:
          list: List
          thumbnails: Thumbnails
        default: list
      columns:
        type: select
        label: Number of columns (thumbnail layout)
        default: 3
        choices:
          1: 1
          2: 2
          3: 3
          4: 4
      show_more_button:
        label: Show more button
        type: checkbox
        default: 1
        help: Display a button that links to the browse wallpapers section with the same order and filter as this module
      more_button_start_page:
        label: More button start page
        type: select
        default: 1
        help: Should the user be directed to the first or second page of results when clicking the more button? Linking to the first page means they will see some of the same results from the module, but linking to the second page might mean they miss a few wallpapers. For best results when linking to page 2, make this module show the same number of wallpapers as is shown per page when browsing.
        choices:
          1: Page One
          2: Page Two
      limit:
        type: text
        label: Number of wallpapers to display
        default: 5
      show_wallpaper_name:
        type: checkbox
        label: Show Name
        default: 1
      show_wallpaper_date:
        type: checkbox
        label: Show Date
        default: 0
      show_wallpaper_hits:
        type: checkbox
        label: Show Hits
        default: 1
      show_wallpaper_downloads:
        type: checkbox
        label: Show Downloads
        default: 1
      show_wallpaper_category:
        type: checkbox
        label: Show Category
        default: 1
      show_wallpaper_comments:
        type: checkbox
        label: Show Comments
        default: 0
  wallpaper_tags:
    name: Wallpaper Tag Cloud
    description: A tag cloud for wallpapers
    controller: Wallpapers::WallpaperModulesController::tagsModule
    cachable: true
    default_cache_time: 43200
    accepted_template_types: [content, panel, none]
    cache_bust_model: Wallpapers
    admin_settings:
      limit:
        type: text
        label: Number of tags to display
        default: 40
  wallpaper_resolutions:
    name: Wallpaper Resolutions
    description: A list of all wallpaper resolutions linked to pages to browse them
    controller: Wallpapers::WallpaperModulesController::resolutionsModule
    cachable: true
    default_cache_time: 43200
    accepted_template_types: [panel, none]
  wallpaper_stats:
    name: Wallpaper Stats
    description: Wallpaper stats like total wallpapers, total downloads etc
    controller: Wallpapers::WallpaperModulesController::wallpaperStatsModule
    cachable: true
    default_cache_time: 43200
    accepted_template_types: [content, panel, none]

config:
    wallpapers_dir: webmaster/wallpapers
    web_dir: wallpapers
