name: Wallpapers
namespace: AVCMS\Bundles\Wallpapers
require:
    - Framework

services:
    - WallpaperServices

assets:
  avcms_wallpapers.js:
    env: admin
    priority: 50

user_settings_sections:
  wallpapers: Wallpapers

user_settings:
  show_higher_resolutions:
    type: checkbox
    label: Show resolutions higher than the source image
    help: If turned on, all resolutions will be displayed for all wallpapers
    section: wallpapers
    default: false

menu_items:
    admin:
        wallpapers_admin:
            label: Wallpapers
            icon: glyphicon glyphicon-picture
            type: route
            default_order: 80
            settings:
              route: wallpapers_admin_home
        wallpapers_bulk_admin:
          label: Bulk Import
          icon: glyphicon glyphicon-import
          type: route
          parent: wallpapers_admin
          settings:
            route: wallpaper_bulk_import_admin_home

categories:
    wallpaper:
        model: AVCMS\Bundles\Wallpapers\Model\WallpaperCategories
        content_model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
        browser_template: @Wallpapers/admin/wallpapers_browser.twig
        route_prefix: wallpapers_

frontend_search:
  wallpapers:
    name: Wallpapers
    route: browse_wallpapers

comments:
  wallpaper:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
    title_field: name
    frontend_route: wallpaper_details
    frontend_route_params: [slug]

ratings:
  wallpaper:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers

permissions:
  ADMIN_WALLPAPERS:
    name: Wallpapers Administration
    description: Manage wallpapers in the admin panel

module_positions:
  wallpapers_home:
    name: Wallpapers Homepage
    environment: frontend
    global_modules: 1
    type: content

modules:
  wallpapers:
    name: Wallpapers
    description: A sortable list of wallpapers
    controller: Wallpapers::WallpaperModulesController::wallpapersListModule
    cachable: true
    cache_bust_model: Wallpapers
    default_cache_time: 10000
    accepted_template_types: [panel, list_panel, none]
    user_settings:
      order:
        type: select
        label: Order
        choices:
          newest: Newest
          top_hits: Top Hits
        default: newest
      limit:
        type: text
        label: Number of wallpapers to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: 0
      show_hits:
        type: checkbox
        label: Show Hits
        default: 1
      show_downloads:
        type: checkbox
        label: Show Downloads
        default: 1
      show_category:
        type: checkbox
        label: Show Category
        default: 1
      layout:
        type: select
        label: Layout
        choices:
          list: List
          thumbnails: Thumbnails
        default: list
      columns:
        type: select
        label: Number of columns (thumbnail layout)
        default: 1
        choices:
          1: 1
          2: 2
          3: 3
          4: 4
  liked_wallpapers:
    name: Liked Wallpapers
    description: A list of a user's liked wallpapers
    controller: Wallpapers::WallpaperModulesController::likedWallpapersModule
    cachable: true
    default_cache_time: 0
    accepted_template_types: [panel, list_panel, none]
    type: user
    user_settings:
      limit:
        type: text
        label: Number of wallpapers to display
        default: 5
      show_date:
        type: checkbox
        label: Show Date
        default: 0
      show_hits:
        type: checkbox
        label: Show Hits
        default: 1
      show_downloads:
        type: checkbox
        label: Show Downloads
        default: 1
      layout:
        type: select
        label: Layout
        choices:
          list: List
          thumbnails: Thumbnails
        default: list
      columns:
        type: select
        label: Number of columns (thumbnail layout)
        default: 1
        choices:
          1: 1
          2: 2
          3: 3
          4: 4

config:
    wallpapers_dir: webmaster/wallpapers
    web_dir: wallpapers
