name: Wallpapers
namespace: AVCMS\Bundles\Wallpapers
require:
    - Framework

services:
    - WallpaperServices

menu_items:
    admin:
        wallpapers_admin:
            label: Wallpapers
            icon: glyphicon glyphicon-picture
            type: route
            target: wallpapers_admin_home
            default_order: 80
        wallpapers_bulk_admin:
          label: Bulk Import
          icon: glyphicon glyphicon-import
          type: route
          target: wallpaper_bulk_import_admin_home
          parent: wallpapers_admin

categories:
    wallpaper:
        model: AVCMS\Bundles\Wallpapers\Model\WallpaperCategories
        content_model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
        browser_template: @Wallpapers/wallpapers_browser.twig
        route_prefix: wallpapers_

frontend_search:
  wallpapers:
    name: Wallpapers
    route: browse_wallpapers

comments:
  wallpaper:
    name: Wallpaper
    model: AVCMS\Bundles\Wallpapers\Model\Wallpapers
    title_field: name
    frontend_route: wallpaper_details
    frontend_route_params: [slug]

config:
    wallpapers_dir: webmaster/wallpapers
    web_dir: wallpapers
