wallpapers:
    bundle: Wallpapers
    namespace: AVCMS\Bundles\Wallpapers
    singular: wallpaper
    plural: wallpapers
    uc_singular: Wallpaper
    uc_plural: Wallpapers
    cc_singular: Wallpaper
    cc_plural: Wallpapers
    dash_singular: wallpaper
    dash_plural: wallpapers
    admin_home_route: wallpapers_admin_home
    admin_finder_route: wallpapers_admin_finder
    admin_delete_route: wallpapers_admin_delete
    admin_edit_route: wallpapers_admin_edit
    admin_add_route: wallpapers_admin_add
    admin_controller: 'Wallpapers::WallpapersAdminController'
    finder_item_extra_buttons: ''
    database: wallpapers
    entity: AVCMS\Bundles\Wallpapers\Model\Wallpaper
    admin_form: AVCMS\Bundles\Wallpapers\Form\WallpaperAdminForm
    model_class: Wallpapers
    model_var_name: wallpapers
    title_field: name
wallpaper_categories:
    bundle: Wallpapers
    namespace: AVCMS\Bundles\Wallpapers
    singular: wallpaper_category
    plural: wallpaper_categories
    uc_singular: 'Wallpaper Category'
    uc_plural: 'Wallpaper Categories'
    cc_singular: WallpaperCategory
    cc_plural: WallpaperCategories
    dash_singular: wallpaper-category
    dash_plural: wallpaper-categories
    admin_home_route: wallpaper_categories_admin_home
    admin_finder_route: wallpaper_categories_admin_finder
    admin_delete_route: wallpaper_categories_admin_delete
    admin_edit_route: wallpaper_categories_admin_edit
    admin_add_route: wallpaper_categories_admin_add
    admin_controller: 'Wallpapers::WallpaperCategoriesAdminController'
    finder_item_extra_buttons: ''
    database: wallpaper_categories
    entity: AVCMS\Bundles\Wallpapers\Model\WallpaperCategory
    admin_form: AVCMS\Bundles\Wallpapers\Form\WallpaperCategoryAdminForm
    model_class: WallpaperCategories
    model_var_name: wallpaperCategories
    title_field: name
wallpaper_bulk_import:
    bundle: Wallpapers
    namespace: AVCMS\Bundles\Wallpapers
    singular: wallpaper_bulk_import
    plural: wallpaper_bulk_import
    uc_singular: 'Wallpaper Bulk Import'
    uc_plural: 'Wallpaper Bulk Import'
    cc_singular: WallpaperBulkImport
    cc_plural: WallpaperBulkImport
    dash_singular: wallpaper-bulk-import
    dash_plural: wallpaper-bulk-import
    admin_home_route: wallpaper_bulk_import_admin_home
    admin_finder_route: wallpaper_bulk_import_admin_finder
    admin_delete_route: wallpaper_bulk_import_admin_delete
    admin_edit_route: wallpaper_bulk_import_admin_edit
    admin_add_route: wallpaper_bulk_import_admin_add
    admin_controller: 'Wallpapers::WallpaperBulkImportAdminController'
    finder_item_extra_buttons: ''
    database: wallpapers
    entity: AVCMS\Bundles\Wallpapers\Model\WallpaperBulkImport
    admin_form: AVCMS\Bundles\Wallpapers\Form\WallpaperBulkImportAdminForm
    model_class: WallpaperBulkImportModel
    model_var_name: wallpaperBulkImport
    title_field: name
wallpaper_submissions:
    bundle: Wallpapers
    namespace: AVCMS\Bundles\Wallpapers
    singular: wallpaper_submission
    plural: wallpaper_submissions
    uc_singular: 'Wallpaper Submission'
    uc_plural: 'Wallpaper Submissions'
    cc_singular: WallpaperSubmission
    cc_plural: WallpaperSubmissions
    dash_singular: wallpaper-submission
    dash_plural: wallpaper-submissions
    admin_home_route: wallpaper_submissions_admin_home
    admin_finder_route: wallpaper_submissions_admin_finder
    admin_delete_route: wallpaper_submissions_admin_delete
    admin_edit_route: wallpaper_submissions_admin_review
    admin_add_route: wallpaper_submissions_admin_add
    admin_controller: 'Wallpapers::WallpaperSubmissionsAdminController'
    finder_item_extra_buttons: ''
    database: wallpaper_submissions
    entity: AVCMS\Bundles\Wallpapers\Model\WallpaperSubmission
    admin_form: AVCMS\Bundles\Wallpapers\Form\WallpaperSubmissionAdminForm
    model_class: WallpaperSubmissions
    model_var_name: wallpaperSubmissions
    title_field: name
