wallpaper_thumbnail:
  path: /web/wallpapers/{id}/thumbnail/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, ext: png }

browse_wallpapers:
  path: /wallpapers
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction }

wallpaper_details:
  path: /wallpapers/{category}/{slug}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperDetailsAction }

wallpaper_preview:
  path: /wallpapers/{category}/{slug}/{resolution}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperPreviewAction }
