wallpapers_home:
  path: /wallpapers
  defaults: { _controller: Wallpapers::WallpapersController::wallpapersHomeAction }

featured_wallpapers:
  path: /wallpapers/featured
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction, pageType: featured }

wallpaper_rss_feed:
  path: /wallpapers/rss.xml
  defaults: { _controller: Wallpapers::WallpapersController::wallpapersRssFeedAction }

wallpaper_thumbnail:
  path: /web/wallpapers/{slug}/thumbnail/{thumbnail_size}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, thumbnail: true }

wallpaper_image:
  path: /web/wallpapers/{slug}/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction }

wallpaper_download:
  path: /wallpapers/{slug}/download/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, download: true }

browse_wallpapers:
  path: /wallpapers/browse/{page}
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction, category: null, page: 1 }
  requirements:
    page:  \d+

wallpaper_submit:
  path: /wallpapers/submit
  defaults: { _controller: Wallpapers::WallpapersController::submitWallpaperAction }

wallpaper_category:
  path: /wallpapers/{category}/{page}
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction, page: 1 }

wallpaper_preview:
  path: /wallpaper/{slug}/{resolution}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperPreviewAction }

wallpaper_details:
  path: /wallpaper/{slug}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperDetailsAction }
