wallpaper_thumbnail:
  path: /web/wallpapers/{id}/thumbnail/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, thumbnail: true }

wallpaper_image:
  path: /wallpapers/{id}/image/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction }

wallpaper_download:
  path: /wallpapers/{id}/download/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, download: true }

wallpaper_category:
  path: /wallpapers/{category}/{page}
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction, category: null, page: 1 }

browse_wallpapers:
  path: /wallpapers/{category}
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction, category: null }

wallpaper_preview:
  path: /wallpaper/{slug}/{resolution}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperPreviewAction }

wallpaper_details:
  path: /wallpaper/{slug}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperDetailsAction }
