wallpaper_thumbnail:
  path: /web/wallpapers/{id}/thumbnailx/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, thumbnail: true }

wallpaper_image:
  path: /wallpapers/{id}/image/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction }

wallpaper_download:
  path: /wallpapers/{id}/download/{width}x{height}.{ext}
  defaults: { _controller: Wallpapers::WallpapersImageController::imageAction, download: true }

browse_wallpapers:
  path: /wallpapers
  defaults: { _controller: Wallpapers::WallpapersController::browseWallpapersAction }

wallpaper_details:
  path: /wallpapers/{category}/{slug}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperDetailsAction }

wallpaper_preview:
  path: /wallpapers/{category}/{slug}/{resolution}
  defaults: { _controller: Wallpapers::WallpapersController::wallpaperPreviewAction }
