name: AVScripts
namespace: AVCMS\Bundles\AVScripts
require:
    - Framework

services:
    - AVScriptsServices

assets:
    avcms_updates.js:
        env: admin

modules:
  avcms_updates:
    name: Updates
    description: Shows if a new version is available
    type: admin
    controller: AVScripts::UpdaterModuleController::updaterModule
    cachable: false
    accepted_template_types: [panel, content, none]
  avcms_news:
    name: AV Scripts News
    description: Shows the latest AV Scripts news
    type: admin
    controller: AVScripts::NewsModuleController::AVSNewsModule
    cachable: true
    default_cache_time: 86400
    accepted_template_types: [panel, none]

container_params:
  avs_api_url: http://localhost:8888/avcms-updates/public

admin_settings:
  copyright_message:
    type: hidden
