pages:
    bundle: Pages
    namespace: AVCMS\Bundles\Pages
    singular: page
    plural: pages
    uc_singular: Page
    uc_plural: Pages
    cc_singular: Page
    cc_plural: Pages
    dash_singular: page
    dash_plural: pages
    admin_home_route: pages_admin_home
    admin_finder_route: pages_admin_finder
    admin_delete_route: pages_admin_delete
    admin_edit_route: pages_admin_edit
    admin_add_route: pages_admin_add
    admin_controller: 'Pages::PagesAdminController'
    finder_item_extra_buttons: ''
    database: pages
    entity: AVCMS\Bundles\Pages\Model\Page
    admin_form: AVCMS\Bundles\Pages\Form\PageAdminForm
    model_class: Pages
    model_var_name: pages
    title_field: title
