versions:
    bundle: Installer
    namespace: AVCMS\Bundles\Installer
    singular: version
    plural: versions
    uc_singular: Version
    uc_plural: Versions
    cc_singular: Version
    cc_plural: Versions
    dash_singular: version
    dash_plural: versions
    admin_home_route: versions_admin_home
    admin_finder_route: versions_admin_finder
    admin_delete_route: versions_admin_delete
    admin_edit_route: versions_admin_edit
    admin_add_route: versions_admin_add
    admin_controller: 'Installer::VersionsAdminController'
    finder_item_extra_buttons: ''
    database: versions
    entity: AVCMS\Bundles\Installer\Model\Version
    admin_form: AVCMS\Bundles\Installer\Form\VersionAdminForm
    model_class: Versions
    model_var_name: versions
    title_field: id
