new_install:
  path: /new
  defaults: { _controller: Installer::InstallerController::newInstallAction }

update_bundles:
  path: /update-bundles
  defaults: { _controller: Installer::InstallerController::updateBundlesAction }

update_bundle:
  path: /update-bundle
  defaults: { _controller: Installer::InstallerController::updateBundleAction }