admin_dashboard:
  path: /
  defaults: { _controller: Admin::AdminDashboardController::dashboardAction }

username_suggest:
  path: /username_suggest
  defaults: {_controller: Admin::AdminHelpersController::usernameSuggestAction' }

generate_slug:
  path: /generate_slug/{title}
  defaults: { _controller: 'Admin::AdminHelpersController::slugGeneratorAction' }