username_suggest:
  path: /username_suggest
  defaults: {_controller: Admin::AdminHelpersController::usernameSuggestAction }

generate_slug:
  path: /generate_slug/{title}
  defaults: { _controller: Admin::AdminHelpersController::slugGeneratorAction }

admin_main_menu:
  path: /main-menu
  defaults: { _controller: Admin::AdminHelpersController::mainMenuAction }
