name: Admin
namespace: AVCMS\Bundles\Admin

require:
  - Framework
  - CmsFoundation
  - Users
  - Assets

assets:
  select2.min.js:
    env: admin
  select2.css:
    env: admin
    priority: 10
  select2-bootstrap.css:
    env: admin
    priority: 5
  jquery.history.js:
    env: admin
  jquery.nanoscroller.min.js:
    env: admin
  nanoscroller.css:
    env: admin
  jquery.mjs.nestedSortable.js:
      env: admin
      compress: false
  jquery.datetimepicker.js:
    env: admin
    compress: false
  jquery.datetimepicker.css:
    env: admin
  jquery-ui.min.js:
    env: admin
    priority: 20
    compress: false

  bootstrap.min.js:
    env: admin
  bootstrap.min.css:
    env: admin
  animate.css:
    env: admin

  admin_navigation.js:
      env: admin
      priority: -100
  admin_browser.js:
      env: admin
      priority: 15
  admin_misc.js:
      env: admin
      priority: 15
  admin_sortable.js:
    env: admin
    priority: 15

  avcms_admin_template.js:
    env: admin
  avcms_admin.css:
    env: admin
    priority: -10

module_positions:
  admin_dashboard:
    name: Admin Dashboard
    description: The admin dashboard
    type: admin
    environment: admin

menu_items:
  admin:
    admin_dashboard:
      icon: glyphicon glyphicon-dashboard
      type: route
      label: Dashboard
      default_order: 1
      settings:
        route: admin_dashboard

services:
  - AdminServices
