manage_comments:
  path: /comments
  defaults: { _controller: Comments::CommentsAdminController::manageCommentsAction }

comments_finder:
  path: /comments/finder
  defaults: { _controller: Comments::CommentsAdminController::commentsFinderAction }
