name: Comments
namespace: AVCMS\Bundles\Comments

services:
  - CommentServices

assets:
  avcms_comments.js:
    env: frontend
  avcms_comments.css:
    env: frontend

permissions:
  PERM_ADD_COMMENT:
    name: Add Comment
    description: Ability to comment throughout the site
  ADMIN_COMMENTS:
    name: Manage Comments
    description: Ability to view & delete comments in the admin and frontend

menu_items:
  admin:
    admin_comments:
      label: Comments
      target: manage_comments
      icon: glyphicon glyphicon-comment
      type: route