name: Comments
namespace: AVCMS\Bundles\Comments

require:
  - Users
  - Admin
  - CmsFoundation
  - Framework

services:
  - CommentServices

reports:
  comments:
    name: Comment
    model: AVCMS\Bundles\Comments\Model\Comments
    content_field: comment
    user_id_field: userId
    route: manage_comments
    route_params: [id]

assets:
  avcms_comments.js:
    env: frontend
  avcms_comments.css:
    env: frontend

permissions:
  PERM_ADD_COMMENT:
    name: Add Comment
    description: Ability to comment throughout the site
  ADMIN_COMMENTS:
    name: Manage Comments
    description: Ability to view & delete comments in the admin and frontend

menu_items:
  admin:
    admin_comments:
      label: Comments
      target: manage_comments
      icon: glyphicon glyphicon-comment
      type: route
      permission: ADMIN_COMMENTS

user_settings:
  comments_enabled:
    label: Enable Comments
    help: Enable/Disable comments of all types
    default: true
    section: main
    type: checkbox
