comments:
    bundle: Comments
    namespace: AVCMS\Bundles\Comments
    singular: comment
    plural: comments
    uc_singular: Comment
    uc_plural: Comments
    cc_singular: Comment
    cc_plural: Comments
    dash_singular: comment
    dash_plural: comments
    admin_home_route: comments_admin_home
    admin_finder_route: comments_admin_finder
    admin_delete_route: comments_admin_delete
    admin_edit_route: comments_admin_edit
    admin_add_route: comments_admin_add
    admin_controller: 'Comments::CommentsAdminController'
    finder_item_extra_buttons: ''
    database: comments
    entity: AVCMS\Bundles\Comments\Model\Comment
    admin_form: AVCMS\Bundles\Comments\Form\CommentAdminForm
    model_class: Comments
    model_var_name: comments
    title_field: id
