users_admin_edit:
  path:     /users/edit/{id}
  defaults: { _controller: 'Users::UsersAdminController::editAction' }

users_admin_delete:
  path:     /users/delete
  defaults: { _controller: 'Users::UsersAdminController::deleteAction' }

users_admin_home:
  path: /users
  defaults: { _controller: 'Users::UsersAdminController::homeAction' }

users_admin_finder:
  path: /users/finder/{page}
  defaults: { page: 1, _controller: 'Users::UsersAdminController::finderAction' }

users_admin_change_password:
  path: /users/change-password/{id}
  defaults: { _controller: Users::UsersAdminController::changePasswordAction }

users_admin_options:
  path: /users/options
  defaults: { _controller: Users::UsersAdminController::userOptionsAction }

users_admin_emails:
  path: /users/emails
  defaults: { _controller: Users::UsersAdminController::userEmailsAction }

user_groups_admin_edit:
    path:     /user-groups/edit/{id}
    defaults: { _controller: 'Users::UserGroupsAdminController::editAction' }

user_groups_admin_add:
    path:     /user-groups/new
    defaults: { _controller: 'Users::UserGroupsAdminController::editAction' }

user_groups_admin_delete:
    path:     /user-groups/delete
    defaults: { _controller: 'Users::UserGroupsAdminController::deleteAction' }

user_groups_admin_home:
  path: /user-groups
  defaults: { _controller: 'Users::UserGroupsAdminController::homeAction' }

user_groups_admin_finder:
  path: /user-groups/finder/{page}
  defaults: { page: 1, _controller: 'Users::UserGroupsAdminController::finderAction' }

user_groups_admin_manage_permissions:
  path: /user-groups/permissions/{id}
  defaults: { _controller: 'Users::UserGroupsAdminController::manageGroupPermissionsAction' }
