name: Users
namespace: AVCMS\Bundles\Users

services:
  - UserServices

core: true

model:
  users: Users
  groups: Groups
  sessions: Sessions
  group_permissions: GroupPermissions

route:
  login: login

template:
  users_browser: @Users/users_browser.twig