name: Users
namespace: AVCMS\Bundles\Users

require:
  - Framework
  - CmsFoundation

services:
  - UserServices
  - SecurityServices
  - UserTwigServices
  - UserMiscServices

core: true

model:
  users: Users
  groups: Groups
  sessions: Sessions
  group_permissions: GroupPermissions

route:
  login: login

user_settings_sections:
  users: Users

user_settings:
  users_enabled:
    label: Enable Users
    type: checkbox
    help: If disabled, users cannot register and any user related-features are disabled.
    default: true
    section: users
  validate_email_addresses:
    label: Validate Emails
    help: If on, a user will need to validate their email address when registering
    type: checkbox
    default: 1
    section: users

assets:
  profile.css:
    env: frontend

module_positions:
  user_profile_main:
      name: User Profile Main
      description: User profile main section
      type: user
      global_modules: 1
  user_profile_sidebar:
    name: User Profile Sidebar
    description: User profile sidebar
    type: user
    global_modules: 1

modules:
  user_info:
    name: User Info
    description: Displays user info like location and 'About Me'
    controller: Users::UserModulesController::userInfoModule
    type: user
    cachable: false

menu_items:
  admin:
    users_admin:
      icon: glyphicon glyphicon-user
      label: Users
      type: route
      target: users_admin_home
    user_groups_admin:
      icon: glyphicon glyphicon-credit-card
      label: Groups
      type: route
      target: user_groups_admin_home
      parent: users_admin

container_params:
  test_var: users.model
  avatar_dir: web/avatars
  avatar_path: web/avatars
  default_access_denied_template: @CmsErrorHandler/error.twig
  access_denied_templates:
    Symfony\Component\Security\Core\Exception\AccessDeniedException: @CmsErrorHandler/error.twig
    AVCMS\Core\Security\Exception\SiteOfflineException: @CmsErrorHandler/site_offline.twig