login:
  path:     /login
  defaults: { _controller: 'Users::UserAuthController::loginAction' }

login_check:
  path:     /login_check

logout:
  path:     /logout

register:
  path:     /register
  defaults: { _controller: 'Users::UserAuthController::registerAction' }

validate_email:
  path:     /validate-email/{userId}/{code}
  defaults: { _controller: 'Users::UserAuthController::validateEmailAction' }

user_profile:
  path: /profile/{slug}
  defaults: { _controller: Users::UserProfileController::userProfileAction }

edit_user_profile:
  path: /edit-profile
  defaults: { _controller: Users::UserProfileController::editUserProfileAction }

user_email_password:
  path: /email-password
  defaults: { _controller: Users::UserProfileController::manageEmailPasswordAction }