info:
  name: AVCMS
  version: '1.0.12'
  id: avcms
  url: http://www.avscripts.net

bundle_dirs:
  AV\Bundles: src/AV/Bundles
  AVCMS\Bundles: src/AVCMS/Bundles
  AVCMS\BundlesDev: src/AVCMS/BundlesDev

default_content_installer: AVCMSDefaultContentInstaller
