Framework:
    enabled: true
Twig:
    enabled: true
Form:
    enabled: true
Model:
    enabled: true
CmsFoundation:
    enabled: true
    config:
        module_positions:
            homepage:
                name: Homepage
                description: 'The main homepage'
                environment: frontend
                global_modules: 1
                type: content
Users:
    enabled: true
Admin:
    enabled: true
Blog:
    enabled: true
Tags:
    enabled: true
Assets:
    enabled: true
Translation:
    enabled: true
Comments:
    enabled: true
CkEditor:
    enabled: true
Reports:
    enabled: true
CmsErrorHandler:
    enabled: true
Wallpapers:
    enabled: true
Games:
    enabled: true
FileUpload:
    enabled: true
Categories:
    enabled: true
LikeDislike:
    enabled: true
Adverts:
    enabled: true
FacebookConnect:
    enabled: true
Sitemaps:
    enabled: true
Recaptcha:
    enabled: true
Referrals:
    enabled: true
Links:
    enabled: true
Pages:
    enabled: true
ContactUs:
    enabled: true
Disqus:
    enabled: true
WssImporter:
    enabled: true
AvaImporter:
    enabled: true
AVScripts:
    enabled: true
Points:
    enabled: true
PrivateMessages:
    enabled: true
Friends:
    enabled: true
BulkUpload:
  enabled: true
