games:
    bundle: Generated
    namespace: AVCMS\Bundles\Generated
    singular: game
    plural: games
    uc_singular: Game
    uc_plural: Games
    admin_home_route: games_admin_home
    admin_finder_route: games_admin_finder
    admin_delete_route: games_admin_delete
    admin_edit_route: games_admin_edit
    admin_add_route: games_admin_add
    admin_controller: 'Generated::GamesAdminController'
    finder_item_extra_buttons: ''
    database: games
    entity: AVCMS\Bundles\Generated\Model\Game
    admin_form: AVCMS\Bundles\Generated\Form\GameAdminForm
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, name: { entity: '1', form_field: text, form_label: Name }, description: { entity: '1', form_field: textarea, form_label: Description }, url: { entity: '1', form_field: none, form_label: Url }, category_id: { entity: '1', form_field: none, form_label: 'Category Id' }, category_parent: { entity: '1', form_field: none, form_label: 'Category Parent' }, hits: { entity: '1', form_field: none, form_label: Hits }, published: { entity: '1', form_field: none, form_label: Published }, user_submit: { entity: '1', form_field: none, form_label: 'User Submit' }, width: { entity: '1', form_field: none, form_label: Width }, height: { entity: '1', form_field: none, form_label: Height }, image: { entity: '1', form_field: none, form_label: Image }, import: { entity: '1', form_field: none, form_label: Import }, filetype: { entity: '1', form_field: none, form_label: Filetype }, instructions: { entity: '1', form_field: none, form_label: Instructions }, mochi: { entity: '1', form_field: none, form_label: Mochi }, rating: { entity: '1', form_field: none, form_label: Rating }, featured: { entity: '1', form_field: none, form_label: Featured }, date_added: { entity: '1', form_field: none, form_label: 'Date Added' }, advert_id: { entity: '1', form_field: none, form_label: 'Advert Id' }, highscores: { entity: '1', form_field: none, form_label: Highscores }, mochi_id: { entity: '1', form_field: none, form_label: 'Mochi Id' }, seo_url: { entity: '1', form_field: none, form_label: 'Seo Url' }, submitter: { entity: '1', form_field: none, form_label: Submitter }, html_code: { entity: '1', form_field: none, form_label: 'Html Code' }, testone__something: { entity: '1', form_field: none, form_label: 'Testone  Something' } }
adverts:
    bundle: Generated
    namespace: AVCMS\Bundles\Generated
    singular: advert
    plural: adverts
    uc_singular: Advert
    uc_plural: Adverts
    admin_home_route: adverts_admin_home
    admin_finder_route: adverts_admin_finder
    admin_delete_route: adverts_admin_delete
    admin_edit_route: adverts_admin_edit
    admin_add_route: adverts_admin_add
    admin_controller: 'Generated::AdvertsAdminController'
    finder_item_extra_buttons: ''
    database: adverts
    entity: AVCMS\Bundles\Generated\Model\Advert
    admin_form: AVCMS\Bundles\Generated\Form\AdvertAdminForm
    title_field: adName
    columns: { id: { entity: '1', form_field: none, form_label: Id }, ad_name: { entity: '1', form_field: text, form_label: Name }, ad_content: { entity: '1', form_field: textarea, form_label: 'Advert HTML' } }
playtomics:
    bundle: Generated
    namespace: AVCMS\Bundles\Generated
    singular: playtomic
    plural: playtomics
    uc_singular: Playtomic
    uc_plural: Playtomics
    cc_singular: Playtomic
    cc_plural: Playtomics
    admin_home_route: playtomics_admin_home
    admin_finder_route: playtomics_admin_finder
    admin_delete_route: playtomics_admin_delete
    admin_edit_route: playtomics_admin_edit
    admin_add_route: playtomics_admin_add
    admin_controller: 'Generated::PlaytomicsAdminController'
    finder_item_extra_buttons: ''
    database: playtomic
    entity: AVCMS\Bundles\Generated\Model\Playtomic
    admin_form: AVCMS\Bundles\Generated\Form\PlaytomicAdminForm
    model_class: Playtomics
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, gametag: { entity: '1', form_field: none, form_label: Gametag }, name: { entity: '1', form_field: text, form_label: Name }, description: { entity: '1', form_field: textarea, form_label: Description }, thumb_url: { entity: '1', form_field: text, form_label: 'Thumb Url' }, file_url: { entity: '1', form_field: text, form_label: 'File Url' }, width: { entity: '1', form_field: none, form_label: Width }, height: { entity: '1', form_field: none, form_label: Height }, author: { entity: '1', form_field: none, form_label: Author }, author_link: { entity: '1', form_field: none, form_label: 'Author Link' }, category: { entity: '1', form_field: none, form_label: Category }, visible: { entity: '1', form_field: none, form_label: Visible }, instructions: { entity: '1', form_field: none, form_label: Instructions }, featured: { entity: '1', form_field: none, form_label: Featured }, tags: { entity: '1', form_field: none, form_label: Tags }, highscores: { entity: '1', form_field: none, form_label: Highscores } }
groups:
    bundle: Generated
    namespace: AVCMS\Bundles\Generated
    singular: group
    plural: groups
    uc_singular: Group
    uc_plural: Groups
    cc_singular: Group
    cc_plural: Groups
    admin_home_route: groups_admin_home
    admin_finder_route: groups_admin_finder
    admin_delete_route: groups_admin_delete
    admin_edit_route: groups_admin_edit
    admin_add_route: groups_admin_add
    admin_controller: 'Generated::GroupsAdminController'
    finder_item_extra_buttons: ''
    database: groups
    entity: AVCMS\Bundles\Generated\Model\Group
    admin_form: AVCMS\Bundles\Generated\Form\GroupAdminForm
    model_class: Groups
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, name: { entity: '1', form_field: text, form_label: Name }, flood_control_time: { entity: '1', form_field: none, form_label: 'Flood Control Time' }, double_post_time: { entity: '1', form_field: none, form_label: 'Double Post Time' } }
