adverts_admin_edit:
    path:     /admin/adverts/edit/{id}
    defaults: { _controller: 'Generated::AdvertsAdminController::editAction' }

adverts_admin_add:
    path:     /admin/adverts/new
    defaults: { _controller: 'Generated::AdvertsAdminController::editAction' }

adverts_admin_delete:
    path:     /admin/adverts/delete
    defaults: { _controller: 'Generated::AdvertsAdminController::deleteAction' }

adverts_admin_home:
  path: /admin/adverts
  defaults: { _controller: 'Generated::AdvertsAdminController::homeAction' }

adverts_admin_finder:
  path: /admin/adverts/finder/{page}
  defaults: { page: 1, _controller: 'Generated::AdvertsAdminController::finderAction' }

games_admin_edit:
    path:     /admin/games/edit/{id}
    defaults: { _controller: 'Generated::GamesAdminController::editAction' }

games_admin_add:
    path:     /admin/games/new
    defaults: { _controller: 'Generated::GamesAdminController::editAction' }

games_admin_delete:
    path:     /admin/games/delete
    defaults: { _controller: 'Generated::GamesAdminController::deleteAction' }

games_admin_home:
  path: /admin/games
  defaults: { _controller: 'Generated::GamesAdminController::homeAction' }

games_admin_finder:
  path: /admin/games/finder/{page}
  defaults: { page: 1, _controller: 'Generated::GamesAdminController::finderAction' }

playtomics_admin_edit:
    path:     /admin/playtomics/edit/{id}
    defaults: { _controller: 'Generated::PlaytomicsAdminController::editAction' }

playtomics_admin_add:
    path:     /admin/playtomics/new
    defaults: { _controller: 'Generated::PlaytomicsAdminController::editAction' }

playtomics_admin_delete:
    path:     /admin/playtomics/delete
    defaults: { _controller: 'Generated::PlaytomicsAdminController::deleteAction' }

playtomics_admin_home:
  path: /admin/playtomics
  defaults: { _controller: 'Generated::PlaytomicsAdminController::homeAction' }

playtomics_admin_finder:
  path: /admin/playtomics/finder/{page}
  defaults: { page: 1, _controller: 'Generated::PlaytomicsAdminController::finderAction' }

groups_admin_edit:
    path:     /admin/groups/edit/{id}
    defaults: { _controller: 'Generated::GroupsAdminController::editAction' }

groups_admin_add:
    path:     /admin/groups/new
    defaults: { _controller: 'Generated::GroupsAdminController::editAction' }

groups_admin_delete:
    path:     /admin/groups/delete
    defaults: { _controller: 'Generated::GroupsAdminController::deleteAction' }

groups_admin_home:
  path: /admin/groups
  defaults: { _controller: 'Generated::GroupsAdminController::homeAction' }

groups_admin_finder:
  path: /admin/groups/finder/{page}
  defaults: { page: 1, _controller: 'Generated::GroupsAdminController::finderAction' }