games_admin_edit:
    path:     /games/edit/{id}
    defaults: { _controller: 'Games::GamesAdminController::editAction' }

games_admin_add:
    path:     /games/new
    defaults: { _controller: 'Games::GamesAdminController::editAction' }

games_admin_delete:
    path:     /games/delete
    defaults: { _controller: 'Games::GamesAdminController::deleteAction' }

games_admin_home:
  path: /games
  defaults: { _controller: 'Games::GamesAdminController::homeAction' }

games_admin_finder:
  path: /games/finder/{page}
  defaults: { page: 1, _controller: 'Games::GamesAdminController::finderAction' }

games_admin_toggle_published:
  path: /games/publish
  defaults: { _controller: Games::GamesAdminController::togglePublishedAction }

games_admin_toggle_featured:
  path: /games/toggle-featured
  defaults: { _controller: Games::GamesAdminController::toggleFeaturedAction }

# Get Dimensions #
games_admin_dimensions:
  path: /games/get-dimensions
  defaults: { _controller: 'Games::GamesAdminController::getDimensionsAction' }

# File Select #
games_admin_find_files:
  path: /games/find-files
  defaults: { _controller: 'Games::GameFilesAdminController::findFilesAction' }

games_admin_upload_file:
  path: /games/upload
  defaults: { _controller: 'Games::GameFilesAdminController::uploadFilesAction' }

games_grab_file:
  path: /games/grab-file
  defaults: { _controller: Games::GameFilesAdminController::grabFileAction }

# Categories #
games_manage_categories:
  path: /games/categories
  defaults: { _controller: 'Games::GamesAdminController::manageCategoriesAction', contentType: game }

games_save_categories_order:
  path: /games/categories/save-order
  defaults: { _controller: Games::GamesAdminController::saveOrderAction, contentType: game }

games_admin_add_category:
  path: /games/categories/new
  defaults: { _controller: Games::GamesAdminController::editCategoryAction, contentType: game }

games_admin_delete_category:
  path: /games/categories/delete/{id}
  defaults: { _controller: Games::GamesAdminController::deleteCategoryAction, contentType: game }

games_admin_edit_category:
  path: /games/categories/edit/{id}
  defaults: { _controller: Games::GamesAdminController::editCategoryAction, contentType: game }

# Game Feeds #
update_game_feeds:
  path:     /game-feeds/update
  defaults: { _controller: 'Games::FeedGamesAdminController::updateFeedsAction' }

download_games_feed:
  path:     /game-feeds/download
  defaults: { _controller: 'Games::FeedGamesAdminController::downloadFeedAction' }

import_feed_game:
  path:     /game-feeds/import
  defaults: { _controller: 'Games::FeedGamesAdminController::importGameAction' }

play_feed_game:
  path:     /game-feeds/play/{id}
  defaults: { _controller: 'Games::FeedGamesAdminController::playGameAction' }

feed_games_admin_delete:
  path:     /game-feeds/delete
  defaults: { _controller: 'Games::FeedGamesAdminController::deleteAction' }

feed_games_admin_home:
  path: /game-feeds
  defaults: { _controller: 'Games::FeedGamesAdminController::homeAction' }

feed_games_admin_finder:
  path: /game-feeds/finder/{page}
  defaults: { page: 1, _controller: 'Games::FeedGamesAdminController::finderAction' }
