name: Games
namespace: AVCMS\Bundles\Games
require:
  - Framework

assets:
  avcms_games_admin.js:
    env: admin

categories:
  game:
    model: AVCMS\Bundles\Games\Model\GameCategories
    content_model: AVCMS\Bundles\Games\Model\Games
    route_prefix: games_

menu_items:
  admin:
    games_admin:
      label: Games
      icon: glyphicon glyphicon-tower
      type: route
      default_order: 2
      settings:
        route: games_admin_home
    games_categories_admin:
      label: Categories
      icon: glyphicon glyphicon-th-list
      type: route
      parent: games_admin
      settings:
        route: games_manage_categories

container_params:
  games_dir: web/games
  game_thumbnails_dir: web/games
