name: Games
namespace: AVCMS\Bundles\Games
require:
  - Framework

services:
  - GamesServices
  - GameFeedServices

assets:
  avcms_games_admin.js:
    env: admin
  avcms_games.js:
    env: frontend
  unity_embed.js:
      env: shared

  avcms_games.css:
    env: frontend

categories:
  game:
    model: AVCMS\Bundles\Games\Model\GameCategories
    content_model: AVCMS\Bundles\Games\Model\Games
    route_prefix: games_

menu_items:
  admin:
    games_admin:
      label: Games
      icon: glyphicon glyphicon-tower
      type: route
      default_order: 2
      settings:
        route: games_admin_home
    games_categories_admin:
      label: Categories
      icon: glyphicon glyphicon-th-list
      type: route
      parent: games_admin
      settings:
        route: games_manage_categories
    games_feeds_admin:
      label: Game Feeds
      icon: glyphicon glyphicon-cloud-download
      type: route
      default_order: 3
      settings:
        route: game_feeds_admin_home

user_settings_sections:
  game_ads: Adverts Before Games
  game_feeds: Game Feeds

user_settings:
  game_ad_default:
    label: Default Game Ad
    help: The ad shown before games without a specific ad selected
    type: select
    default: 0
    choices:
      0: None
    choices_provider_service: adverts.choices_provider
    section: game_ads
  game_ad_countdown:
    label: Game Ads Duration
    help: How long to show the advert before the game automatically loads
    type: text
    default: 15
    section: game_ads
    validation:
      numeric:
        rule: Numeric
  game_ad_allow_skip:
    label: Allow Skipping
    help: Allow users to skip the ads
    type: checkbox
    default: 1
    section: game_ads
  game_ad_show_to_everyone:
    label: Ignore Permission
    help: Who sees ads before games can be set in the group permissions area. When this is on, everyone sees the ads regardless of that permission.
    type: checkbox
    default: 0
    section: game_ads
  game_feed_limit:
    type: text
    label: Game Feed Limit
    help: The number of games to fetch when updating a game feed
    default: 1000
    section: game_feeds
  download_feed_games:
    type: checkbox
    label: Download Games
    help: Download game files & thumbnails to your server. If off, files will be hotlinked.
    default: 1
    section: game_feeds
  get_feed_game_tags:
    type: checkbox
    label: Get Tags
    help: If a feed has tags, apply them to games when downloading. Can result in a lot of tags building up.
    default: 0
    section: game_feeds

comments:
  game:
    name: Game
    model: AVCMS\Bundles\Games\Model\Games
    title_field: name
    frontend_route: play_game
    frontend_route_params: [slug]

reports:
  games:
    name: Game
    model: AVCMS\Bundles\Games\Model\Games
    route: games_admin_edit
    title_field: name
    route_params: [id]

ratings:
  game:
    name: Game
    model: AVCMS\Bundles\Games\Model\Games

module_positions:
  beside_game_comments:
      name: Beside Game Comments
      description: Next to the game comments
      environment: frontend
      global_modules: 1
      type: content

permissions:
  ELEVATED_NO_GAME_ADS:
    name: No Game Adverts
    description: If allowed, users in this group will not see ads before games

container_params:
  games_dir: web/games
  game_thumbnails_dir: web/game-thumbnails
