name: Games
namespace: AVCMS\Bundles\Games
toggle: true
require:
  - Framework

services:
  - GamesServices
  - GameFeedServices

assets:
  avcms_games_admin.js:
    env: admin
  avcms_games.js:
    env: shared
  unity_embed.js:
    env: shared

  avcms_games.css:
    env: frontend

categories:
  game:
    model: AVCMS\Bundles\Games\Model\GameCategories
    content_model: AVCMS\Bundles\Games\Model\Games
    route_prefix: games_

menu_items:
  frontend:
    game_categories:
      label: Games
      icon: glyphicon glyphicon-tower
      type: game_categories
      default_order: 2
      settings:
        display: child
    game_submissions:
      label: Submit Game
      icon: glyphicon glyphicon-upload
      type: route
      admin_setting: games_allow_uploads
      settings:
        route: submit_game
  admin:
    games_admin:
      label: Games
      icon: glyphicon glyphicon-tower
      type: route
      default_order: 2
      permission: ADMIN_GAMES
      settings:
        route: games_admin_home
    games_categories_admin:
      label: Categories
      icon: glyphicon glyphicon-th-list
      type: route
      parent: games_admin
      settings:
        route: games_manage_categories
    games_submissions_admin:
      label: Submissions
      icon: glyphicon glyphicon-inbox
      type: route
      permission: ADMIN_GAMES
      parent: games_admin
      settings:
        route: game_submissions_admin_home
    games_feeds_admin:
      label: Game Feeds
      icon: glyphicon glyphicon-cloud-download
      type: route
      default_order: 3
      permission: ADMIN_GAMES
      settings:
        route: game_feeds_admin_home

admin_settings_sections:
  games: Games
  browse_games: Browse Games
  game_ads: Adverts Before Games
  game_feeds: Game Feeds

admin_settings:
  games_allow_uploads:
    type: checkbox
    label: Allow Game Submissions
    help: Allow users to submit games to your site for admins to review
    section: games
    default: 0
  games_max_submissions:
    type: text
    label: Maximum User Submissions
    help: The maximum amount of games a user can submit for review. They can submit more after an admin has accepted their existing submissions.
    section: games
    default: 5
    validation:
      numeric:
        rule: Numeric
  game_ad_default:
    label: Default Game Ad
    help: The ad shown before games without a specific ad selected
    type: select
    default: 0
    choices:
      0: None
    choices_provider_service: adverts.choices_provider
    section: game_ads
  game_ad_countdown:
    label: Game Ads Duration
    help: How long to show the advert before the game automatically loads
    type: text
    default: 15
    section: game_ads
    validation:
      numeric:
        rule: Numeric
  game_ad_allow_skip:
    label: Allow Skipping
    help: Allow users to skip the ads
    type: checkbox
    default: 1
    section: game_ads
  game_ad_show_to_everyone:
    label: Ignore Permission
    help: Who sees ads before games can be set in the group permissions area. When this is on, everyone sees the ads regardless of that permission.
    type: checkbox
    default: 0
    section: game_ads
  games_limit_plays:
    label: Limit Game Plays
    help: The number of games that can be played before a user must register an account
    type: text
    default: 0
    section: games
  game_feed_limit:
    type: text
    label: Game Feed Limit
    help: The number of games to fetch when updating a game feed
    default: 1000
    section: game_feeds
  download_feed_games:
    type: checkbox
    label: Download Games
    help: Download game files & thumbnails to your server. If off, files will be hotlinked.
    default: 1
    section: game_feeds
  get_feed_game_tags:
    type: checkbox
    label: Get Tags
    help: If a feed has tags, apply them to games when downloading. Can result in a lot of tags building up.
    default: 0
    section: game_feeds
  browse_games_layout:
    type: select
    label: Browse Games Layout
    choices:
      details: Details
      thumbnail: Thumbnail
    default: details
    section: browse_games
  browse_games_columns:
    type: select
    label: Browse Games Columns
    choices:
      1: 1
      2: 2
      3: 3
      4: 4
    default: 2
    section: browse_games
  browse_games_per_page:
    type: text
    label: Games Per Page
    help: Number of games to show per page (browse, categories etc)
    default: 20
    section: browse_games
  show_game_description:
    type: checkbox
    label: Show Description
    default: 1
    section: browse_games
  show_game_ratings:
    type: checkbox
    label: Show Game Ratings
    default: 1
    section: browse_games
  show_game_hits:
    type: checkbox
    label: Show Game Hits
    default: 1
    section: browse_games
  show_game_date:
    type: checkbox
    label: Show Publish Date
    default: 0
    section: browse_games
  show_game_category:
    type: checkbox
    label: Show Category
    default: 0
    section: browse_games
  show_game_comments:
    type: checkbox
    label: Show Total Comments
    default: 0
    section: browse_games

comments:
  game:
    name: Game
    model: AVCMS\Bundles\Games\Model\Games
    title_field: name
    frontend_route: play_game
    frontend_route_params: [slug]

reports:
  games:
    name: Game
    model: AVCMS\Bundles\Games\Model\Games
    route: games_admin_edit
    title_field: name
    route_params: [id]

ratings:
  game:
    name: Game
    model: AVCMS\Bundles\Games\Model\Games

frontend_search:
  games:
    name: Games
    route: browse_games

module_positions:
  games_home:
    name: Games Homepage
    description: The games homepage
    environment: frontend
    global_modules: 1
    type: content
  play_game_sidebar:
      name: Play Game Sidebar
      description: Sidebar on the play game page
      environment: frontend
      global_modules: 1
      type: content

modules:
  games:
    name: Games
    description: A customisable list of games
    controller: Games::GameModulesController::gamesModule
    cachable: true
    cache_bust_model: Games
    default_cache_time: 3600
    accepted_template_types: [content, panel, list_panel, none]
    admin_settings:
      filter:
        type: select
        label: Filter
        help: If "User's Likes" is selected, the module will show the likes of a user if one is passed to the module position (like on a users profile). Otherwise it will show the active user's likes.
        default: none
        choices:
          none: None
          featured: Featured
          likes: User's Likes
      layout:
        type: select
        label: Layout
        choices:
          list: List
          thumbnails: Thumbnails
          details: Details
        default: list
      columns:
        type: select
        label: Number of columns (thumbnail/details layout)
        default: 3
        choices:
          1: 1
          2: 2
          3: 3
          4: 4
      order:
        type: select
        label: Order
        choices:
          publish-date-newest: Newest
          top-hits: Most Played
          liked: Most Liked
          random: Random
        default: newest
      limit:
        type: text
        label: Number of games to display
        default: 5
      show_game_description:
        type: checkbox
        label: Show Description
        default: 1
      show_game_date:
        type: checkbox
        label: Show Date
        default: 0
      show_game_hits:
        type: checkbox
        label: Show Hits
        default: 1
      show_game_ratings:
        type: checkbox
        label: Show Ratings
        default: 1
      show_game_category:
        type: checkbox
        label: Show Category
        default: 1
      show_game_comments:
        type: checkbox
        label: Show Total Comments
        default: 0
  game_tags:
      name: Game Tag Cloud
      description: A tag cloud for games
      controller: Games::GameModulesController::tagsModule
      cachable: true
      default_cache_time: 43200
      accepted_template_types: [content, panel, none]
      admin_settings:
        limit:
          type: text
          label: Number of tags to display
          default: 40

permissions:
  ELEVATED_NO_GAME_ADS:
    name: No Game Adverts
    description: If allowed, users in this group will not see ads before games
  ADMIN_GAMES:
    name: Games Administration
    description: Manage games in the admin panel (including categories & game feeds)
  PERM_SUBMIT_GAMES:
    name: Submit Games
    description: Can submit games to the site for admins to review & accept

container_params:
  games_dir: web/games
  game_thumbnails_dir: web/game-thumbnails
