games:
    bundle: Games
    namespace: AVCMS\Bundles\Games
    singular: game
    plural: games
    uc_singular: Game
    uc_plural: Games
    cc_singular: Game
    cc_plural: Games
    dash_singular: game
    dash_plural: games
    admin_home_route: games_admin_home
    admin_finder_route: games_admin_finder
    admin_delete_route: games_admin_delete
    admin_edit_route: games_admin_edit
    admin_add_route: games_admin_add
    admin_controller: 'Games::GamesAdminController'
    finder_item_extra_buttons: ''
    database: games
    entity: AVCMS\Bundles\Games\Model\Game
    admin_form: AVCMS\Bundles\Games\Form\GameAdminForm
    model_class: Games
    model_var_name: games
    title_field: name
game_categories:
    bundle: Games
    namespace: AVCMS\Bundles\Games
    singular: game_category
    plural: game_categories
    uc_singular: 'Game Category'
    uc_plural: 'Game Categories'
    cc_singular: GameCategory
    cc_plural: GameCategories
    dash_singular: game-category
    dash_plural: game-categories
    admin_home_route: game_categories_admin_home
    admin_finder_route: game_categories_admin_finder
    admin_delete_route: game_categories_admin_delete
    admin_edit_route: game_categories_admin_edit
    admin_add_route: game_categories_admin_add
    admin_controller: 'Games::GameCategoriesAdminController'
    finder_item_extra_buttons: ''
    database: game_categories
    entity: AVCMS\Bundles\Games\Model\GameCategory
    admin_form: AVCMS\Bundles\Games\Form\GameCategoryAdminForm
    model_class: GameCategories
    model_var_name: gameCategories
    title_field: name
game_embeds:
    bundle: Games
    namespace: AVCMS\Bundles\Games
    singular: game_embed
    plural: game_embeds
    uc_singular: 'Game Embed'
    uc_plural: 'Game Embeds'
    cc_singular: GameEmbed
    cc_plural: GameEmbeds
    dash_singular: game-embed
    dash_plural: game-embeds
    admin_home_route: game_embeds_admin_home
    admin_finder_route: game_embeds_admin_finder
    admin_delete_route: game_embeds_admin_delete
    admin_edit_route: game_embeds_admin_edit
    admin_add_route: game_embeds_admin_add
    admin_controller: 'Games::GameEmbedsAdminController'
    finder_item_extra_buttons: ''
    database: game_embeds
    entity: AVCMS\Bundles\Games\Model\GameEmbed
    admin_form: AVCMS\Bundles\Games\Form\GameEmbedAdminForm
    model_class: GameEmbeds
    model_var_name: gameEmbeds
    title_field: id
feed_games:
    bundle: Games
    namespace: AVCMS\Bundles\Games
    singular: feed_game
    plural: feed_games
    uc_singular: 'Feed Game'
    uc_plural: 'Feed Games'
    cc_singular: FeedGame
    cc_plural: FeedGames
    dash_singular: feed-game
    dash_plural: feed-games
    admin_home_route: game_feeds_admin_home
    admin_finder_route: game_feeds_admin_finder
    admin_delete_route: game_feeds_admin_reject
    admin_edit_route: feed_games_admin_edit
    admin_add_route: feed_games_admin_add
    admin_controller: 'Games::FeedGamesAdminController'
    finder_item_extra_buttons: ''
    database: feed_games
    entity: AVCMS\Bundles\Games\Model\FeedGame
    admin_form: AVCMS\Bundles\Games\Form\FeedGameAdminForm
    model_class: FeedGames
    model_var_name: feedGames
    title_field: name
