games:
    bundle: Games
    namespace: AVCMS\Bundles\Games
    singular: game
    plural: games
    uc_singular: Game
    uc_plural: Games
    cc_singular: Game
    cc_plural: Games
    dash_singular: game
    dash_plural: games
    admin_home_route: games_admin_home
    admin_finder_route: games_admin_finder
    admin_delete_route: games_admin_delete
    admin_edit_route: games_admin_edit
    admin_add_route: games_admin_add
    admin_controller: 'Games::GamesAdminController'
    finder_item_extra_buttons: ''
    database: games
    entity: AVCMS\Bundles\Games\Model\Game
    admin_form: AVCMS\Bundles\Games\Form\GameAdminForm
    model_class: Games
    model_var_name: games
    title_field: name
