games_home:
  path: /games
  defaults: { _controller: CmsFoundation::HomepageController::homepageAction, modulePosition: games_home, title: Games }

play_game:
  path: /game/{slug}
  defaults: { _controller: Games::GamesController::playGameAction }

browse_games:
  path: /games/browse/{page}
  defaults: { _controller: Games::GamesController::browseGamesAction, category: null, page: 1 }
  requirements:
    page:  \d+

game_tag:
  path: /games/tag/{tags}
  defaults: { _controller: Games::GamesController::browseGamesAction, category: null, page: 1 }
  requirements:
    page:  \d+

featured_games:
  path: /games/featured
  defaults: { _controller: Games::GamesController::browseGamesAction, pageType: featured }

liked_games:
  path: /games/likes/{likes_user}
  defaults: { _controller: Games::GamesController::browseGamesAction, pageType: likes, likes_user: null }

games_rss_feed:
  path: /games/rss.xml
  defaults: { _controller: Games::GamesController::gamesRssFeedAction }

game_category:
  path: /games/{category}/{page}
  defaults: { _controller: Games::GamesController::browseGamesAction, page: 1 }
