Framework:
  enabled: true
Model:
  enabled: true
  config:
    container_params:
      database_config_location: app/config/database.php
Twig:
  enabled: true
Form:
  enabled: true
Installer:
  enabled: true