images:
    bundle: Images
    namespace: AVCMS\Bundles\Images
    singular: image
    plural: images
    uc_singular: Image
    uc_plural: Images
    cc_singular: Image
    cc_plural: Images
    dash_singular: image
    dash_plural: images
    admin_home_route: images_admin_home
    admin_finder_route: images_admin_finder
    admin_delete_route: images_admin_delete
    admin_edit_route: images_admin_edit
    admin_add_route: images_admin_add
    admin_controller: 'Images::ImagesAdminController'
    finder_item_extra_buttons: ''
    database: images
    entity: AVCMS\Bundles\Images\Model\Image
    admin_form: AVCMS\Bundles\Images\Form\ImageAdminForm
    model_class: Images
    model_var_name: images
    title_field: name
image_categories:
    bundle: Images
    namespace: AVCMS\Bundles\Images
    singular: image_category
    plural: image_categories
    uc_singular: 'Image Category'
    uc_plural: 'Image Categories'
    cc_singular: ImageCategory
    cc_plural: ImageCategories
    dash_singular: image-category
    dash_plural: image-categories
    admin_home_route: image_categories_admin_home
    admin_finder_route: image_categories_admin_finder
    admin_delete_route: image_categories_admin_delete
    admin_edit_route: image_categories_admin_edit
    admin_add_route: image_categories_admin_add
    admin_controller: 'Images::ImageCategoriesAdminController'
    finder_item_extra_buttons: ''
    database: image_categories
    entity: AVCMS\Bundles\Images\Model\ImageCategory
    admin_form: AVCMS\Bundles\Images\Form\ImageCategoryAdminForm
    model_class: ImageCategories
    model_var_name: imageCategories
    title_field: name
image_embeds:
    bundle: Images
    namespace: AVCMS\Bundles\Images
    singular: image_embed
    plural: image_embeds
    uc_singular: 'Image Embed'
    uc_plural: 'Image Embeds'
    cc_singular: ImageEmbed
    cc_plural: ImageEmbeds
    dash_singular: image-embed
    dash_plural: image-embeds
    admin_home_route: image_embeds_admin_home
    admin_finder_route: image_embeds_admin_finder
    admin_delete_route: image_embeds_admin_delete
    admin_edit_route: image_embeds_admin_edit
    admin_add_route: image_embeds_admin_add
    admin_controller: 'Images::ImageEmbedsAdminController'
    finder_item_extra_buttons: ''
    database: image_embeds
    entity: AVCMS\Bundles\Images\Model\ImageEmbed
    admin_form: AVCMS\Bundles\Images\Form\ImageEmbedAdminForm
    model_class: ImageEmbeds
    model_var_name: imageEmbeds
    title_field: id
feed_images:
    bundle: Images
    namespace: AVCMS\Bundles\Images
    singular: feed_image
    plural: feed_images
    uc_singular: 'Feed Image'
    uc_plural: 'Feed Images'
    cc_singular: FeedImage
    cc_plural: FeedImages
    dash_singular: feed-image
    dash_plural: feed-images
    admin_home_route: image_feeds_admin_home
    admin_finder_route: image_feeds_admin_finder
    admin_delete_route: image_feeds_admin_reject
    admin_edit_route: feed_images_admin_edit
    admin_add_route: feed_images_admin_add
    admin_controller: 'Images::ImageFeedsAdminController'
    finder_item_extra_buttons: ''
    database: feed_images
    entity: AVCMS\Bundles\Images\Model\FeedImage
    admin_form: AVCMS\Bundles\Images\Form\FeedImageAdminForm
    model_class: FeedImages
    model_var_name: feedImages
    title_field: name
image_files:
    bundle: Images
    namespace: AVCMS\Bundles\Images
    singular: image_file
    plural: image_files
    uc_singular: 'Image File'
    uc_plural: 'Image Files'
    cc_singular: ImageFile
    cc_plural: ImageFiles
    dash_singular: image-file
    dash_plural: image-files
    admin_home_route: image_files_admin_home
    admin_finder_route: image_files_admin_finder
    admin_delete_route: image_files_admin_delete
    admin_edit_route: image_files_admin_edit
    admin_add_route: image_files_admin_add
    admin_controller: 'Images::ImageFilesAdminController'
    finder_item_extra_buttons: ''
    database: image_files
    entity: AVCMS\Bundles\Images\Model\ImageFile
    admin_form: AVCMS\Bundles\Images\Form\ImageFileAdminForm
    model_class: ImageFiles
    model_var_name: imageFiles
    title_field: id
