name: Links
namespace: AVCMS\Bundles\Links
require:
    - Framework

services:
    - LinksServices

menu_items:
    admin:
        admin_links:
            label: Links
            icon: glyphicon glyphicon-link
            type: route
            permission: ADMIN_LINKS
            default_order: 80
            settings:
                route: links_admin_home

permissions:
  ADMIN_LINKS:
    name: Links Administration
    description: Ability to manage links

modules:
  links:
    name: Links
    description: The top links from link exchanges
    controller: Links::LinksModuleController::linksModule
    cachable: true
    cache_bust_model: Links
    default_cache_time: 3600
    accepted_template_types: [list_panel, none]
    admin_settings:
      total_links:
        type: text
        label: Links to show
        default: 10

admin_settings_sections:
  links: Links

admin_settings:
  link_exchange:
    label: Enable Link Exchange
    type: checkbox
    section: links
    default: 1
  link_exchange_no_follow:
    label: Make Link Exchange Links 'No Follow'
    type: checkbox
    help: If links are set to nofollow, search engines will not follow the link
    section: links
    default: 1
