link_exchange:
  path: /link-exchange
  defaults: { _controller: Links::LinksController::linkExchangeAction }

links:
  path: /links
  defaults: { _controller: Links::LinksController::linksAction }

link_out:
  path: /links/go/{id}
  defaults: { _controller: Links::LinksController::linkOutAction }
