friend_requests:
    bundle: Friends
    namespace: AVCMS\Bundles\Friends
    singular: friend_request
    plural: friend_requests
    uc_singular: 'Friend Request'
    uc_plural: 'Friend Requests'
    cc_singular: FriendRequest
    cc_plural: FriendRequests
    dash_singular: friend-request
    dash_plural: friend-requests
    admin_home_route: friend_requests_admin_home
    admin_finder_route: friend_requests_admin_finder
    admin_delete_route: friend_requests_admin_delete
    admin_edit_route: friend_requests_admin_edit
    admin_add_route: friend_requests_admin_add
    admin_controller: 'Friends::FriendRequestsAdminController'
    finder_item_extra_buttons: ''
    database: friend_requests
    entity: AVCMS\Bundles\Friends\Model\FriendRequest
    admin_form: AVCMS\Bundles\Friends\Form\FriendRequestAdminForm
    model_class: FriendRequests
    model_var_name: friendRequests
    title_field: id
friends:
    bundle: Friends
    namespace: AVCMS\Bundles\Friends
    singular: friend
    plural: friends
    uc_singular: Friend
    uc_plural: Friends
    cc_singular: Friend
    cc_plural: Friends
    dash_singular: friend
    dash_plural: friends
    admin_home_route: friends_admin_home
    admin_finder_route: friends_admin_finder
    admin_delete_route: friends_admin_delete
    admin_edit_route: friends_admin_edit
    admin_add_route: friends_admin_add
    admin_controller: 'Friends::FriendsAdminController'
    finder_item_extra_buttons: ''
    database: friends
    entity: AVCMS\Bundles\Friends\Model\Friend
    admin_form: AVCMS\Bundles\Friends\Form\FriendAdminForm
    model_class: Friends
    model_var_name: friends
    title_field: id
