name: PrivateMessages
namespace: AVCMS\Bundles\PrivateMessages
toggle: true
require:
    - Framework

services:
  - PrivateMessageServices

assets:
  avcms_messages.js:
    env: frontend

permissions:
  PERM_PRIVATE_MESSAGES:
    name: Private Messages
    description: Ability to send and receive private messages
