private_messages:
    bundle: PrivateMessages
    namespace: AVCMS\Bundles\PrivateMessages
    singular: private_message
    plural: private_messages
    uc_singular: 'Private Message'
    uc_plural: 'Private Messages'
    cc_singular: PrivateMessage
    cc_plural: PrivateMessages
    dash_singular: private-message
    dash_plural: private-messages
    admin_home_route: private_messages_admin_home
    admin_finder_route: private_messages_admin_finder
    admin_delete_route: private_messages_admin_delete
    admin_edit_route: private_messages_admin_edit
    admin_add_route: private_messages_admin_add
    admin_controller: 'PrivateMessages::PrivateMessagesAdminController'
    finder_item_extra_buttons: ''
    database: messages
    entity: AVCMS\Bundles\PrivateMessages\Model\PrivateMessage
    admin_form: AVCMS\Bundles\PrivateMessages\Form\PrivateMessageAdminForm
    model_class: PrivateMessages
    model_var_name: privateMessages
    title_field: id
