avcms_settings:
  path: /settings
  defaults: { _controller: CmsFoundation::SettingsAdminController::indexAction }

menus_admin_edit:
    path:     /menus/edit/{id}
    defaults: { _controller: 'CmsFoundation::MenusAdminController::editMenuAction' }

menus_admin_add:
    path:     /menus/new
    defaults: { _controller: 'CmsFoundation::MenusAdminController::editMenuAction' }

menus_admin_delete:
    path:     /menus/delete
    defaults: { _controller: 'CmsFoundation::MenusAdminController::deleteMenuAction' }

menus_admin_home:
  path: /menus
  defaults: { _controller: 'CmsFoundation::MenusAdminController::homeAction' }

menus_admin_finder:
  path: /menus/finder/{page}
  defaults: { page: 1, _controller: 'CmsFoundation::MenusAdminController::finderAction' }

menus_admin_manage_items:
    path:     /menus/manage/{id}
    defaults: { _controller: 'CmsFoundation::MenusAdminController::manageMenuItemsAction' }

menus_save_order:
  path: /menus/save-order/{id}
  defaults: { _controller: CmsFoundation::MenusAdminController::saveOrderAction }

menu_items_select:
  path: /menus/{menu}/new
  defaults: { _controller: CmsFoundation::MenusAdminController::selectMenuItemAction }

menu_items_add:
  path: /menus/{menu}/new/{type}
  defaults: { _controller: CmsFoundation::MenusAdminController::editMenuItemAction }

menu_items_edit:
  path: /menus/{menu}/{id}
  defaults: { _controller: CmsFoundation::MenusAdminController::editMenuItemAction }

menus_admin_delete_item:
  path: /menus/delete-item
  defaults: { _controller: CmsFoundation::MenusAdminController::deleteMenuItemAction }

toggle_menu_item_enabled:
  path: /menus/publish
  defaults: { _controller: CmsFoundation::MenusAdminController::toggleMenuItemEnabledAction }

modules_admin_edit:
    path:     /modules/edit/{id}
    defaults: { _controller: 'CmsFoundation::ModulesAdminController::manageSelectedModuleAction' }

modules_admin_add:
    path:     /modules/{position}/add
    defaults: { _controller: 'CmsFoundation::ModulesAdminController::addModuleAction' }

modules_admin_add_selected:
    path:     /modules/{position}/add/{module}
    defaults: { _controller: 'CmsFoundation::ModulesAdminController::manageSelectedModuleAction' }

modules_admin_delete:
    path:     /modules/delete
    defaults: { _controller: 'CmsFoundation::ModulesAdminController::deleteAction' }

modules_admin_home:
  path: /modules
  defaults: { _controller: 'CmsFoundation::ModulesAdminController::homeAction' }

modules_admin_finder:
  path: /modules/finder/{page}
  defaults: { page: 1, _controller: 'CmsFoundation::ModulesAdminController::finderAction' }

modules_manage_position:
  path: /modules/manage/{id}
  defaults: { _controller: 'CmsFoundation::ModulesAdminController::managePositionModulesAction' }

modules_save_order:
  path: /modules/save-order/{position}
  defaults: { _controller: 'CmsFoundation::ModulesAdminController::saveOrderAction' }

modules_delete_position:
  path: /modules/delete-position
  defaults: { _controller: 'CmsFoundation::ModulesAdminController::deletePositionAction' }

modules_get_template_styles:
  path: /modules/template-styles/{positionId}/{templateType}
  defaults: { _controller: 'CmsFoundation::ModulesAdminController::getTemplatesListAction' }

modules_admin_toggle_published:
  path: /modules/publish
  defaults: { _controller: 'CmsFoundation::ModulesAdminController::togglePublishedAction' }

clear_caches:
  path: /clear-caches
  defaults: { _controller: CmsFoundation::ClearCachesController::clearCachesAction }

manage_templates_admin_home:
  path: /templates
  defaults: { _controller: 'CmsFoundation::EditTemplatesAdminController::homeAction' }

manage_templates_admin_finder:
  path: /templates/finder/{page}
  defaults: { page: 1, _controller: 'CmsFoundation::EditTemplatesAdminController::finderAction' }

manage_templates_admin_edit:
  path: /templates/edit/{bundle}/{file}
  defaults: { page: 1, _controller: 'CmsFoundation::EditTemplatesAdminController::editAction' }

manage_templates_admin_reset:
  path: /templates/reset
  defaults: { page: 1, _controller: 'CmsFoundation::EditTemplatesAdminController::resetTemplateAction' }
