name: CmsFoundation
namespace: AVCMS\Bundles\CmsFoundation

core: true

services:
  - SettingsServices
  - TemplateServices
  - DatabaseServices
  - TwigServices
  - BundleServices
  - TranslationServices
  - TaxonomyServices
  - FormServices
  - MenuServices
  - ModuleServices

user_settings_sections:
  main: Main

user_settings:
  site_name:
    type: text
    label: Site Name
    default: My AVCMS Site
    section: main
  template:
    type: select
    choices_provider: { class: AVCMS\Bundles\CmsFoundation\Settings\TemplateChoicesProvider }
    label: Template
    help: The frontend template
    section: main
    default: indigo

assets:
  jquery.js:
    env: shared
    priority: 90
  bootstrap.min.js:
    env: shared
  bootstrap.min.css:
    env: shared
  avcms_form.js:
    env: shared
  avcms_event.js:
    env: shared
    priority: 89

menu_items:
  admin:
    modules:
      target: modules_admin_home
      icon: glyphicon glyphicon-list-alt
      type: route
      label: Modules

modules:
  my_module:
    controller: 'CmsFoundation::BaseModulesController::firstModuleAction'
    name: My New Module
    description: This is my first module and it's pretty great huh?
    user_settings:
            my_settings:
              type: text
              default: Lol
              label: A custom setting
              required: true

require:
  - Framework
  - NonExistant