name: CmsFoundation
namespace: AVCMS\Bundles\CmsFoundation

core: true

require:
  - Framework

services:
  - SettingsServices
  - TemplateServices
  - TaxonomyServices
  - MenuServices
  - ModuleServices
  - EmailServices
  - HitCounterServices
  - MiscServices

admin_settings_sections:
  main: Main
  email: Email

admin_settings:
  site_name:
    type: text
    label: Site Name
    default: AVCMS
    section: main
    required: true
    validation:
      min_length:
        class: AV\Validation\Rules\Length
        arguments:
          - 5
  site_tagline:
    type: text
    label: Site Tag Line
    section: main
    help: This will be displayed in the page title of the homepage
  site_description:
    type: textarea
    label: Site Description
    section: main
  site_offline:
    type: checkbox
    label: Site Offline
    help: Make your site offline, only accessible to admins
    type: checkbox
    default: 0
    section: main
  site_offline_message:
    type: text
    label: Site Offline Message
    default: Down for maintenance, back soon!
    section: main

  site_email_address:
    type: text
    label: Site "From" Address
    default: admin@yoursite.com
    section: email
    validation:
      Email:
        rule: EmailAddress
  use_smtp:
    type: checkbox
    label: Use SMTP
    section: email
    default: 0
  smtp_username:
    type: text
    label: SMTP Username
    section: email
  smtp_password:
    type: password
    label: SMTP Password
    section: email
  smtp_port:
    type: text
    label: SMTP Port
    section: email
  smtp_server:
    type: text
    label: SMTP Server
    section: email
  smtp_encryption:
      type: select
      label: SMTP Encryption
      section: email
      choices:
        none: None
        ssl: SSL
        tls: TLS
  admin_emails:
    type: text
    label: Admin Emails
    help: Email addresses to send admin emails to, separated by a comma
    section: email

  template:
    type: select
    choices_provider_service: template_choices_provider
    label: Template
    help: The frontend template
    section: main
    default: webmaster/templates/frontend/spark
  email_template:
    type: select
    choices_provider_service: email_template_choices_provider
    label: Email Template
    help: The template for emails sent from your site
    section: main
    default: webmaster/templates/email/avcms
  language:
    type: select
    choices_provider: { class: AVCMS\Bundles\CmsFoundation\Settings\LanguageChoicesProvider }
    choices_translate: false
    label: Site Language
    help: The default site language
    section: main
    default: en
  date_format:
    type: text
    label: Date Format
    default: Y-m-d
    section: main
    required: true
  time_format:
    type: text
    label: Time Format
    default: Y-m-d H:i
    section: main
    required: true
  google_analytics_id:
    type: text
    label: Google Analytics ID
    help: The ID of your Google Analytics campaign

  show_module_buttons:
    type: checkbox
    label: Show Module Buttons
    help: Show buttons on the frontend to quickly access editing module positions
    default: 0
    section: main

assets:
  jquery.js:
    env: shared
    priority: 90
    compress: false
  bootstrap.min.js:
    env: frontend
    compress: false
  bootstrap.min.css:
    env: frontend
    priority: 90
  avcms_form.js:
    env: shared
  avcms_event.js:
    env: shared
    priority: 89
  avcms_menus_admin.js:
    env: admin
  avcms_modules_admin.js:
      env: admin
  avcms_bundles_admin.js:
      env: admin
  notify.min.js:
    env: shared
    compress: false
  avcms_misc.js:
    env: shared
  avcms_frontend.js:
    env: frontend
  avcms_templates.js:
    env: admin
  avcms_codemirror.js:
    env: admin
    priority: -15
  codemirror.css:
      env: admin

menus:
  frontend:
    label: Frontend
  admin:
    label: Admin

menu_items:
  admin:
    settings:
      icon: glyphicon glyphicon-cog
      type: route
      label: Settings
      default_order: 120
      permission: ADMIN_SETTINGS
      settings:
        route: avcms_settings
    admin_templates:
      icon: glyphicon glyphicon-file
      type: route
      label: Edit Templates
      parent: settings
      settings:
        route: manage_templates_admin_home
    modules:
      icon: glyphicon glyphicon-list-alt
      type: route
      label: Modules
      parent: settings
      permission: ADMIN_MODULES
      settings:
        route: modules_admin_home
    menus:
      icon: glyphicon glyphicon-th-list
      type: route
      label: Menus
      parent: settings
      permission: ADMIN_MENUS
      settings:
        route: menus_admin_home
    bundles:
      icon: glyphicon glyphicon-modal-window
      type: route
      label: Bundles
      parent: settings
      permission: ADMIN_BUNDLES
      settings:
        route: manage_bundles_admin

modules:
  html_module:
    controller: 'CmsFoundation::BaseModulesController::htmlModule'
    name: HTML Snippet
    description: Add a HTML block to this position
    cachable: true
    default_cache_time: 1000000
    accepted_template_types: [panel, content, none]
    admin_settings:
      html:
        type: textarea
        label: HTML
        required: true
  menu_module:
    controller: CmsFoundation::MenuModulesController::menuModule
    name: Menu
    description: Display a menu
    cachable: true
    default_cache_time: 3600
    cache_bust_model: MenuItems
    accepted_template_types: [list_panel, none]
    admin_settings:
      menu:
        type: select
        label: Menu
        choices_provider_service: form.menu_choices_provider
        default: newest
      type:
        type: select
        label: Type
        choices:
          list: List
          buttons: Buttons
        default: buttons
      button_size:
        type: select
        label: Button Size (Button Type)
        choices:
          xs: Extra Small
          sm: Small
          md: Medium
          lg: Large
        default: md
      button_style:
        label: Button Style (Button Type)
        type: select
        choices:
          default: Default
          link: Link
          primary: Primary
        default: default

module_positions:
  homepage:
    name: Homepage
    description: 'The main homepage'
    environment: frontend
    global_modules: 1
    type: content

permissions:
  ADMIN_CLEAR_CACHES:
    name: Clear Caches
    description: Clear app caches
  ADMIN_MENUS:
    name: Manage Menus
    description: Manage menus in the admin panel
  ADMIN_MODULES:
    name: Manage Modules
    description: Manage modules in the admin panel
  ADMIN_SETTINGS:
    name: Admin Settings
    description: Manage the site settings in the admin panel
  ADMIN_EDIT_TEMPLATES:
    name: Edit Templates
    description: Edit template files in the admin panel
  ADMIN_BUNDLES:
    name: Manage Bundles
    description: Manage installed bundles, toggle features on/off
