name: CmsFoundation
namespace: AVCMS\Bundles\CmsFoundation

core: true

require:
  - Framework

services:
  - SettingsServices
  - TemplateServices
  - TaxonomyServices
  - MenuServices
  - ModuleServices
  - EmailServices
  - HitCounterServices
  - MiscServices

user_settings_sections:
  main: Main
  email: Email

user_settings:
  site_name:
    type: text
    label: Site Name
    default: My AVCMS Site
    section: main
    required: true
    validation:
      min_length:
        class: AV\Validation\Rules\Length
        arguments:
          - 5

  site_email_address:
    type: text
    label: Site "From" Address
    default: admin@yoursite.com
    section: email
    validation:
      Email:
        rule: EmailAddress
  smtp_username:
    type: text
    label: SMTP Username
    section: email
  smtp_password:
    type: password
    label: SMTP Password
    section: email
  smtp_port:
    type: text
    label: SMTP Port
    section: email
  smtp_server:
    type: text
    label: SMTP Server
    section: email
  smtp_encryption:
      type: select
      label: SMTP Encryption
      section: email
      choices:
        none: None
        ssl: SSL
        tls: TLS


  template:
    type: select
    choices_provider: { class: AVCMS\Bundles\CmsFoundation\Settings\TemplateChoicesProvider }
    label: Template
    help: The frontend template
    section: main
    default: templates/frontend/blog-default
  language:
    type: select
    choices_provider: { class: AVCMS\Bundles\CmsFoundation\Settings\LanguageChoicesProvider }
    label: Site Language
    help: The default site language
    section: main
    default: en
  date_format:
    type: text
    label: Date Format
    default: Y-m-d
    section: main
    required: true

assets:
  jquery.js:
    env: shared
    priority: 90
  bootstrap.min.js:
    env: frontend
  bootstrap.min.css:
    env: frontend
  avcms_form.js:
    env: shared
  avcms_event.js:
    env: shared
    priority: 89
  avcms_menus_admin.js:
    env: admin
  avcms_modules_admin.js:
      env: admin
  notify.min.js:
    env: shared
  avcms_misc.js:
    env: shared
  avcms_frontend.js:
    env: frontend

menus:
  frontend:
    label: Frontend
  admin:
    label: Admin

menu_items:
  admin:
    modules:
      target: modules_admin_home
      icon: glyphicon glyphicon-list-alt
      type: route
      label: Modules
      parent: settings
      permission: ADMIN_MODULES
    menus:
      target: menus_admin_home
      icon: glyphicon glyphicon-th-list
      type: route
      label: Menus
      parent: settings
      permission: ADMIN_MENUS
    settings:
      target: avcms_settings
      icon: glyphicon glyphicon-cog
      type: route
      label: Settings
      default_order: 120
      permission: ADMIN_SETTINGS

modules:
  html_module:
    controller: 'CmsFoundation::BaseModulesController::htmlModule'
    name: HTML Snippet
    description: Add a HTML block to this position
    cachable: true
    default_cache_time: 600
    user_settings:
            html:
              type: textarea
              label: HTML
              required: true

permissions:
  ADMIN_CLEAR_CACHES:
    name: Clear Caches
    description: Clear app caches
  ADMIN_MENUS:
    name: Manage Menus
    description: Manage menus in the admin panel
  ADMIN_MODULES:
    name: Manage Modules
    description: Manage modules in the admin panel
  ADMIN_SETTINGS:
    name: Admin Settings
    description: Manage the site settings in the admin panel
