name: CmsFoundation
namespace: AVCMS\Bundles\CmsFoundation

core: true

services:
  - SettingsServices
  - TemplateServices
  - DatabaseServices
  - TwigServices
  - BundleServices
  - TranslationServices
  - TaxonomyServices
  - FormServices
  - MenuServices
  - ModuleServices
  - EmailServices

user_settings_sections:
  main: Main

user_settings:
  site_name:
    type: text
    label: Site Name
    default: My AVCMS Site
    section: main
    validation:
      min_length:
        class: AVCMS\Core\Validation\Rules\Length
        arguments:
          - 5

  template:
    type: select
    choices_provider: { class: AVCMS\Bundles\CmsFoundation\Settings\TemplateChoicesProvider }
    label: Template
    help: The frontend template
    section: main
    default: templates/frontend/indigo

assets:
  jquery.js:
    env: shared
    priority: 90
  bootstrap.min.js:
    env: shared
  bootstrap.min.css:
    env: shared
  avcms_form.js:
    env: shared
  avcms_event.js:
    env: shared
    priority: 89
  avcms_menus_admin.js:
    env: admin

menu_items:
  admin:
    modules:
      target: modules_admin_home
      icon: glyphicon glyphicon-list-alt
      type: route
      label: Modules

modules:
  html_module:
    controller: 'CmsFoundation::BaseModulesController::htmlModule'
    name: HTML Snippet
    description: Add a HTML block to this position
    template_style: plain
    cachable: true
    default_cache_time: 600
    user_settings:
            html:
              type: textarea
              label: HTML
              required: true

require:
  - Framework
  - NonExistant