menu_items:
    bundle: CmsFoundation
    namespace: AVCMS\Bundles\CmsFoundation
    singular: menu_item
    plural: menu_items
    uc_singular: 'Menu Item'
    uc_plural: 'Menu Items'
    cc_singular: MenuItem
    cc_plural: MenuItems
    admin_home_route: menu_items_admin_home
    admin_finder_route: menu_items_admin_finder
    admin_delete_route: menu_items_admin_delete
    admin_edit_route: menu_items_admin_edit
    admin_add_route: menu_items_admin_add
    admin_controller: 'CmsFoundation::MenuItemsAdminController'
    finder_item_extra_buttons: ''
    database: menu_items
    entity: AVCMS\Bundles\CmsFoundation\Model\MenuItem
    admin_form: AVCMS\Bundles\CmsFoundation\Form\MenuItemAdminForm
    model_class: MenuItems
    title_field: id
    columns: { id: { entity: '1', form_field: none, form_label: Id }, menu_id: { entity: '1', form_field: none, form_label: 'Menu Id' }, identifier: { entity: '1', form_field: none, form_label: Identifier }, type: { entity: '1', form_field: none, form_label: Type }, label: { entity: '1', form_field: none, form_label: Label }, target: { entity: '1', form_field: none, form_label: Target }, icon: { entity: '1', form_field: none, form_label: Icon }, parent: { entity: '1', form_field: none, form_label: Parent }, enabled: { entity: '1', form_field: none, form_label: Enabled }, order: { entity: '1', form_field: none, form_label: Order }, owner: { entity: '1', form_field: none, form_label: Owner } }

menus:
    bundle: Admin
    namespace: AVCMS\Bundles\Admin
    singular: menu
    plural: menus
    uc_singular: Menu
    uc_plural: Menus
    cc_singular: Menu
    cc_plural: Menus
    admin_home_route: menus_admin_home
    admin_finder_route: menus_admin_finder
    admin_delete_route: menus_admin_delete
    admin_edit_route: menus_admin_edit
    admin_add_route: menus_admin_add
    admin_controller: 'Admin::MenusAdminController'
    finder_item_extra_buttons: ''
    database: menus
    entity: AVCMS\Bundles\CmsFoundation\Model\Menu
    admin_form: AVCMS\Bundles\CmsFoundation\Form\MenuAdminForm
    model_class: Menus
    title_field: label
    columns: { id: { entity: '1', form_field: none, form_label: Id }, identifier: { entity: '1', form_field: text, form_label: Identifier }, label: { entity: '1', form_field: text, form_label: Label } }