menu_items:
    bundle: CmsFoundation
    namespace: AVCMS\Bundles\CmsFoundation
    singular: menu_item
    plural: menu_items
    uc_singular: 'Menu Item'
    uc_plural: 'Menu Items'
    cc_singular: MenuItem
    cc_plural: MenuItems
    admin_home_route: menu_items_admin_home
    admin_finder_route: menu_items_admin_finder
    admin_delete_route: menu_items_admin_delete
    admin_edit_route: menu_items_admin_edit
    admin_add_route: menu_items_admin_add
    admin_controller: 'CmsFoundation::MenuItemsAdminController'
    finder_item_extra_buttons: ''
    database: menu_items
    entity: AVCMS\Bundles\CmsFoundation\Model\MenuItem
    admin_form: AVCMS\Bundles\CmsFoundation\Form\MenuItemAdminForm
    model_class: MenuItems
    title_field: id
    columns: { id: { entity: '1', form_field: none, form_label: Id }, menu_id: { entity: '1', form_field: none, form_label: 'Menu Id' }, identifier: { entity: '1', form_field: none, form_label: Identifier }, type: { entity: '1', form_field: none, form_label: Type }, label: { entity: '1', form_field: none, form_label: Label }, target: { entity: '1', form_field: none, form_label: Target }, icon: { entity: '1', form_field: none, form_label: Icon }, parent: { entity: '1', form_field: none, form_label: Parent }, enabled: { entity: '1', form_field: none, form_label: Enabled }, order: { entity: '1', form_field: none, form_label: Order }, owner: { entity: '1', form_field: none, form_label: Owner } }
menus:
    bundle: Admin
    namespace: AVCMS\Bundles\Admin
    singular: menu
    plural: menus
    uc_singular: Menu
    uc_plural: Menus
    cc_singular: Menu
    cc_plural: Menus
    admin_home_route: menus_admin_home
    admin_finder_route: menus_admin_finder
    admin_delete_route: menus_admin_delete
    admin_edit_route: menus_admin_edit
    admin_add_route: menus_admin_add
    admin_controller: 'Admin::MenusAdminController'
    finder_item_extra_buttons: ''
    database: menus
    entity: AVCMS\Bundles\CmsFoundation\Model\Menu
    admin_form: AVCMS\Bundles\CmsFoundation\Form\MenuAdminForm
    model_class: Menus
    title_field: label
    columns: { id: { entity: '1', form_field: none, form_label: Id }, identifier: { entity: '1', form_field: text, form_label: Identifier }, label: { entity: '1', form_field: text, form_label: Label } }
module_positions:
    bundle: CmsFoundation
    namespace: AVCMS\Bundles\CmsFoundation
    singular: module_position
    plural: module_positions
    uc_singular: 'Module Position'
    uc_plural: 'Module Positions'
    cc_singular: ModulePosition
    cc_plural: ModulePositions
    admin_home_route: module_positions_admin_home
    admin_finder_route: module_positions_admin_finder
    admin_delete_route: module_positions_admin_delete
    admin_edit_route: module_positions_admin_edit
    admin_add_route: module_positions_admin_add
    admin_controller: 'CmsFoundation::ModulesAdminController'
    finder_item_extra_buttons: ''
    database: module_positions
    entity: AVCMS\Bundles\CmsFoundation\Model\ModulePosition
    admin_form: AVCMS\Bundles\CmsFoundation\Form\ModulePositionAdminForm
    model_class: ModulePositions
    model_var_name: modulePositions
    title_field: name
    columns: { id: { entity: '1', form_field: none, form_label: Id }, name: { entity: '1', form_field: none, form_label: Name }, description: { entity: '1', form_field: none, form_label: Description }, active: { entity: '1', form_field: none, form_label: Active }, provider: { entity: '1', form_field: none, form_label: Provider }, owner: { entity: '1', form_field: none, form_label: Owner } }
Modules:
    bundle: CmsFoundation
    namespace: AVCMS\Bundles\CmsFoundation
    singular: Module
    plural: Modules
    uc_singular: Module
    uc_plural: Modules
    cc_singular: Module
    cc_plural: Modules
    dash_singular: Module
    dash_plural: Modules
    admin_home_route: Modules_admin_home
    admin_finder_route: Modules_admin_finder
    admin_delete_route: Modules_admin_delete
    admin_edit_route: Modules_admin_edit
    admin_add_route: Modules_admin_add
    admin_controller: 'CmsFoundation::ModulesAdminController'
    finder_item_extra_buttons: ''
    database: modules
    entity: AVCMS\Bundles\CmsFoundation\Model\Module
    admin_form: AVCMS\Bundles\CmsFoundation\Form\ModuleAdminForm
    model_class: Modules
    model_var_name: modules
    title_field: id
    columns: { id: { entity: '1', form_field: none, form_label: Id }, module: { entity: '1', form_field: none, form_label: Module }, position: { entity: '1', form_field: none, form_label: Position }, config: { entity: '1', form_field: none, form_label: Config }, active: { entity: '1', form_field: none, form_label: Active } }
hits:
    bundle: CmsFoundation
    namespace: AVCMS\Bundles\CmsFoundation
    singular: hit
    plural: hits
    uc_singular: Hit
    uc_plural: Hits
    cc_singular: Hit
    cc_plural: Hits
    dash_singular: hit
    dash_plural: hits
    admin_home_route: hits_admin_home
    admin_finder_route: hits_admin_finder
    admin_delete_route: hits_admin_delete
    admin_edit_route: hits_admin_edit
    admin_add_route: hits_admin_add
    admin_controller: 'CmsFoundation::HitsAdminController'
    finder_item_extra_buttons: ''
    database: hits
    entity: AVCMS\Bundles\CmsFoundation\Model\Hit
    admin_form: AVCMS\Bundles\CmsFoundation\Form\HitAdminForm
    model_class: Hits
    model_var_name: hits
    title_field: id
