name: Adverts
namespace: AVCMS\Bundles\Adverts
require:
  - Framework

services:
  - AdvertServices

menu_items:
  admin:
    admin_adverts:
      type: route
      label: Adverts
      icon: glyphicon glyphicon-certificate
      permission: ADMIN_ADVERTS
      settings:
        route: adverts_admin_home

modules:
    advert:
        name: Advert
        description: Display an advert from the adverts section
        controller: Adverts::AdvertModulesController::advertModule
        cachable: true
        cache_bust_model: Adverts
        default_cache_time: 3600
        accepted_template_types: [panel, content, none]
        admin_settings:
          advert_id:
            type: select
            label: Advert
            choices_provider_service: adverts.choices_provider

permissions:
  ADMIN_ADVERTS:
    name: Adverts Administration
    description: Manage adverts in the admin panel
