adverts:
    bundle: Adverts
    namespace: AVCMS\Bundles\Adverts
    singular: advert
    plural: adverts
    uc_singular: Advert
    uc_plural: Adverts
    cc_singular: Advert
    cc_plural: Adverts
    dash_singular: advert
    dash_plural: adverts
    admin_home_route: adverts_admin_home
    admin_finder_route: adverts_admin_finder
    admin_delete_route: adverts_admin_delete
    admin_edit_route: adverts_admin_edit
    admin_add_route: adverts_admin_add
    admin_controller: 'Adverts::AdvertsAdminController'
    finder_item_extra_buttons: ''
    database: adverts
    entity: AVCMS\Bundles\Adverts\Model\Advert
    admin_form: AVCMS\Bundles\Adverts\Form\AdvertAdminForm
    model_class: Adverts
    model_var_name: adverts
    title_field: name
