info:
  name: AVCMS Dev
  version: '1.0.10'
  id: avcms_dev
  url: http://www.avscripts.net

bundle_dirs:
  AV\Bundles: src/AV/Bundles
  AVCMS\Bundles: src/AVCMS/Bundles
  AVCMS\BundlesDev: src/AVCMS/BundlesDev

default_content_installer: AVCMSDefaultContentInstaller
